### ISSUE TITLE
Evaluate building a native image

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1068]
Let's see what sorts of errors/failures we have when trying to build a native image for the registry.  Note: I suggested a collaboration between Fabian and Carles for this based on a recent team meeting, but feel free to change the assignment if I remembered incorrectly.

**Comment by famartinrh** [comment]
It could be possible to build a native image for the registry. I thought it was going to be much more difficult. After some testing I found issues with kafka dependencies, which were easy to fix using official quarkus extension for kafka, and another issue with JDBI (the library we are using for the sql storage).

The issue with JDBI is a bit more complicated because I cannot find an official extension nor a working example of a quarkus app using JDBI that compiles to native. The issue is in class `org.jdbi.v3.core.config.ConfigRegistry` .
The errors look like
```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Invoke with MethodHandle argument could not be reduced to at most a single call or single field access. The method handle must be a compile time constant, e.g., be loaded from a `static final` field. Method that contains the method handle invocation: java.lang.invoke.MethodHandle.invokeBasic(Object)
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The error is then reported at run time when the invoke is executed.
Trace: 
	at parsing java.lang.invoke.LambdaForm$MH/0x00000007c2385040.invokeExact_MT(LambdaForm$MH)
Call path from entry point to java.lang.invoke.LambdaForm$MH/477570431.invokeExact_MT(Object, Object, Object): 
	at java.lang.invoke.LambdaForm$MH/0x00000007c2385040.invokeExact_MT(LambdaForm$MH)
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$null$2(ConfigRegistry.java:89)
	at org.jdbi.v3.core.config.ConfigRegistry$$Lambda$1080/0x00000007c2495840.apply(Unknown Source)
	at org.jdbi.v3.core.internal.exceptions.Unchecked.lambda$function$4(Unchecked.java:76)
	at org.jdbi.v3.core.internal.exceptions.Unchecked$$Lambda$1054/0x00000007c248e840.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type java.lang.invoke.MemberName is reachable: All methods from java.lang.invoke should have been replaced during image building.
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Trace: 
	at parsing java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1264)
Call path from entry point to java.lang.invoke.MethodHandles$Lookup.findConstructor(Class, MethodType): 
	at java.lang.invoke.MethodHandles$Lookup.findConstructor(MethodHandles.java:1260)
	at org.jdbi.v3.core.config.ConfigRegistry.lambda$configFactory$4(ConfigRegistry.java:86)
	at org.jdbi.v3.core.config.ConfigRegistry$$Lambda$1058/0x00000007c248fc40.apply(Unknown Source)
	at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:190)
	at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:143)
	at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:331)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)

```

The changes I made can be found in [this branch](https://github.com/famartinrh/apicurio-registry/tree/native-image) , at the bottom of the README some commands can be found to build the native image

**Comment by carlesarnal** [comment]
Hi @EricWittmann, I have one doubt with this. is this a blocker for the MAS initiative? Or it is just a nice to have?

**Comment by EricWittmann** [comment]
Damn - I thought it would be OK to use JDBI because it's a rather simple library.  We could probably drop JDBI in favor of just plain old JDBC.  I would need to do some experimenting.

@carlesarnal This is not a blocker for MAS.

**Comment by famartinrh** [comment]
anyway, don't get crazy trying to get the registry compiled to native. AFAIK with quarkus native compilation is not as memory efficient as JVM in long running processes such as the registry. Native compilation is more suited for serverless workloads

**Comment by famartinrh** [comment]
probably I was wrong about native compiled apps as long running processes.
https://quarkus.io/blog/runtime-performance/
This blog says it clear `Native images are not just for short running processes. The tests ran for up to 3 hours, without process restarts, and the native image served over 33 MILLION requests!`

**Comment by carlesarnal** [comment]
@famartinrh what's the status of this? Is it possible right now to build the native image using the extension you've created?

**Comment by famartinrh** [comment]
this is on hold, it's not possible yet to build a native image. The extension needed is for JDBI not the extension I already created.

**Comment by EricWittmann** [comment]
When we have some more time, it would be really nice to get a native image working so we can do some performance testing.  Not a high priority right now, but let's keep this one warm on the back-burner.

**Comment by EricWittmann** [comment]
I suggest taking a break on this activity.  It might make more sense to just cut JDBI out of the picture.  We're not really using it for very much, and it **might** be easy enough to get rid of it.  In its place I could write a few classes that essentially mimicked the few things we actually use it for (connection handler, resultset handler, etc).

Thoughts?

**Comment by famartinrh** [comment]
I like you highlighted that it **might** be easy enough, I'm ok with giving that approach a try, but do it in a new branch as an experiment.

Also I wonder if there isn't already a quarkus extension that allows to do very low level SQL stuff

**Comment by EricWittmann** [comment]
Yes - doing the work on a branch for sure.

I haven't seen a low level SQL extension for Quarkus (Hibernate and Panache are the options afaik), but that may be due to a lack of looking. :)

**Comment by famartinrh** [comment]
maybe this https://quarkus.io/guides/reactive-sql-clients ?

**Comment by EricWittmann** [comment]
Yeah I saw that - not sure about using the reactive SQL client in a non-reactive Quarkus app.  That might work fine, it might not.  What I would really like to do in the future after things settle down a bit, is start thinking about Registry 3.0 - which I think we should re-engineer to be reactive.  I didn't think it was important originally, but not that we have multi-tenancy I think it would be a good idea.  When we do THAT, then reactive SQL is going to be important.  Hopefully there is also a reactive Kafka client.
