### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by harshsp31** [Apicurio/apicurio-registry#1376]
Hi, 
I am quite new at this so forgive me if this sounds stupid but I can't seem to perform `mvn clean install` successfully. 

I  get the following error:

```
1) Could not find a suitable constructor in kr.motd.maven.os.DetectExtension. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at kr.motd.maven.os.DetectExtension.class(Unknown Source)
  while locating kr.motd.maven.os.DetectExtension
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@7852e922]
  at ClassRealm[extension>kr.motd.maven:os-maven-plugin:1.7.0, parent: sun.misc.Launcher$AppClassLoader@7852e922]
  while locating org.apache.maven.AbstractMavenLifecycleParticipant annotated with @com.google.inject.name.Named(value=detect-os)

1 error
	at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java:1006)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException

```

**Comment by harshsp31** [comment]
Turns out I had to upgrade maven to 3.6.3
