### ISSUE TITLE
Maven plugin call ends with ssl exception

### ISSUE THREAD

**Issue by tszappanos** [Apicurio/apicurio-registry#1418]
Repeated calling of two executions in one pom (first for goal register, second for download) ends in an exception. It only happens with a call via https. Via http and a separate call is ok. Is it not possible that the ssl connection on the client is not closed ? 

Plugin settings:
> <plugin>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-maven-plugin</artifactId>
    <version>2.0.0.RC1</version>
    <executions>
        <execution>
            <id>1</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>register</goal>
            </goals>
            <configuration>
                <registryUrl>${registry.url}</registryUrl>
                <artifactType>AVRO</artifactType>
                <artifacts>
                    <artifact>
                        <groupId>cz.kb.api</groupId>
                        <artifactId>testTopic-TestSchema</artifactId>
                        <file>testSchema.avsc</file>
                        <ifExists>RETURN_OR_UPDATE</ifExists>
                    </artifact>
                </artifacts>
            </configuration>
        </execution>
        <execution>
            <id>2</id>
            <phase>generate-sources</phase>
            <goals>
                <goal>download</goal>
            </goals>
            <configuration>
                <registryUrl>${registry.url}</registryUrl>
                <artifacts>
                    <artifact>
                        <groupId>cz.kb.api</groupId>
                        <artifactId>testTopic-TestSchema</artifactId>
                        <file>test.avsc</file>
                        <overwrite>true</overwrite>
                    </artifact>
                </artifacts>
                <outputDirectory>.</outputDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>

error
> [INFO] --- apicurio-registry-maven-plugin:2.0.0.RC1:register (1) @ dummy ---
[INFO] Successfully registered artifact [cz.kb.api] / [testTopic-TestSchema].  GlobalId is [3801088]
[INFO]
[INFO] --- apicurio-registry-maven-plugin:2.0.0.RC1:download (2) @ dummy ---
[INFO] Downloading artifact [xx.yy.api] / [testTopic-TestSchema] (version null).
[ERROR] Exception while downloading artifact [xx.yy.api] / [testTopic-TestSchema]
io.apicurio.registry.rest.client.exception.RestClientException
    at io.apicurio.registry.rest.client.request.ErrorHandler.parseError (ErrorHandler.java:101)
    at io.apicurio.registry.rest.client.request.RequestHandler.sendRequest (RequestHandler.java:204)
    at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getLatestArtifact (RegistryClientImpl.java:72)
    at io.apicurio.registry.maven.DownloadRegistryMojo.executeInternal (DownloadRegistryMojo.java:97)
    at io.apicurio.registry.maven.AbstractRegistryMojo.execute (AbstractRegistryMojo.java:58)

nested exception

> recorded jdk.internal.net.http.common.ConnectionExpiredException: subscription is finished
     delegate: jdk.internal.net.http.Http1Response$HeadersReader@2c1b9e4b         queue.isEmpty: true jdk.internal.net.http.common.ConnectionExpiredException: subscription is finished
jdk.internal.net.http.common.ConnectionExpiredException: subscription is finished
    at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.onReadError(Http1AsyncReceiver.java:485)
    at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onError(Http1AsyncReceiver.java:585)
    at java.net.http/jdk.internal.net.http.common.SSLTube$DelegateWrapper.onError(SSLTube.java:249)
    at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.complete(SSLTube.java:412)
    at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onErrorImpl(SSLTube.java:481)
    at java.net.http/jdk.internal.net.http.common.SSLTube$SSLSubscriberWrapper.onComplete(SSLTube.java:537)
    at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.checkCompletion(SubscriberWrapper.java:443)
    at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run1(SubscriberWrapper.java:322)
    at java.net.http/jdk.internal.net.http.common.SubscriberWrapper$DownstreamPusher.run(SubscriberWrapper.java:261)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:271)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:224)
    at java.net.http/jdk.internal.net.http.common.SubscriberWrapper.outgoing(SubscriberWrapper.java:234)
    at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader.processData(SSLFlowDelegate.java:467)
    at java.net.http/jdk.internal.net.http.common.SSLFlowDelegate$Reader$ReaderDownstreamPusher.run(SSLFlowDelegate.java:263)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SynchronizedRestartableTask.run(SequentialScheduler.java:175)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:147)
    at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:198)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
    ... 18 more

**Comment by tszappanos** [comment]
Just change the client variable in the AbstractRegistryMojo class to static and it will start working. Can you fix it, please?

**Comment by carlesarnal** [comment]
hi @tszappanos, [this](https://github.com/Apicurio/apicurio-registry/pull/1429) should fix the issue, correct?

**Comment by tszappanos** [comment]
@carlesarnal , yes
