### ISSUE TITLE
InvalidStateStoreException when using Kafka as registry store

### ISSUE THREAD

**Issue by shuawest** [Apicurio/apicurio-registry#1483]
When I use Kafka/Streams as the Apicurio store following the Apicurio documentation, it works for some time, but then eventually but consistently returns an error stating [2] "InvalidStateStoreException: The state store, storage-store, may have migrated to another instance.".  

[1] https://www.apicur.io/registry/docs/apicurio-registry/1.3.3.Final/getting-started/assembly-installing-registry-storage-openshift.html#setting-up-kafka-streams-storage

[2]
```
io.grpc.StatusRuntimeException: FAILED_PRECONDITION: org.apache.kafka.streams.errors.InvalidStateStoreException: The state store, storage-store, may have migrated to another instance.
	at org.apache.kafka.streams.state.internals.QueryableStoreProvider.getStore(QueryableStoreProvider.java:64)
	at org.apache.kafka.streams.KafkaStreams.store(KafkaStreams.java:1183)
	at io.apicurio.registry.utils.streams.distore.KeyValueStoreGrpcImplLocalDispatcher.lambda$keyValueStore$0(KeyValueStoreGrpcImplLocalDispatcher.java:57)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.apicurio.registry.utils.streams.distore.KeyValueStoreGrpcImplLocalDispatcher.keyValueStore(KeyValueStoreGrpcImplLocalDispatcher.java:51)
	at io.apicurio.registry.utils.streams.distore.KeyValueStoreGrpcImplLocalDispatcher.filter(KeyValueStoreGrpcImplLocalDispatcher.java:83)
	at io.apicurio.registry.utils.streams.distore.proto.KeyValueStoreGrpc$MethodHandlers.invoke(KeyValueStoreGrpc.java:588)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:721)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by EricWittmann** [comment]
@carlesarnal @alesj This is something that has popped up in the past, right?  I can't recall if there was a resolution...

**Comment by carlesarnal** [comment]
[Here](https://github.com/Apicurio/apicurio-registry/issues/1241)'s the only workaround I'm aware of. We're not following on it since we've removed the streams storage in `2.0.0.final`

**Comment by EricWittmann** [comment]
@shuawest are you in a position where you can upgrade to 2.0.0.Final, at least to test whether this error occurs?

**Comment by carlesarnal** [comment]
Closing this one as we removed support for the streams storage.
