### ISSUE TITLE
Schema registry not working as expected when using confluent kafka python

### ISSUE THREAD

**Issue by Akhilj786** [Apicurio/apicurio-registry#1491]
Description
===========
Versions:
python 3.8.8

Observing issues with confluent kafka python library leveraging apicurio registry

Version:
https://www.apicur.io/registry/docs/apicurio-registry/2.0.0.Final/index.html

How to reproduce

================

Sample code:
```

class ProtoBufAIOProducer:
    def __init__(self, configs,value_ser=None, loop=None):
        self._loop = loop or asyncio.get_event_loop()
        # self._producer = AvroProducer(configs, default_key_schema=schema_key, default_value_schema=schema_value)
        schema_registry_client = SchemaRegistryClient(
            {'url': configs['schema.registry.url'],
             })
        protobuf_serializer = ProtobufSerializer(value_ser, schema_registry_client)

        self.producer_conf = {'bootstrap.servers': configs['bootstrap.servers'],
                              'key.serializer': StringSerializer('utf_8'),
                              'value.serializer': protobuf_serializer
                              }

        self._producer = SerializingProducer(self.producer_conf)
        self._cancelled = False
        self._poll_thread = Thread(target=self._poll_loop)
        self._poll_thread.start()

    def _poll_loop(self):
        while not self._cancelled:
            self._producer.poll(0.1)

    def close(self):
        self._cancelled = True
        self._poll_thread.join()

    def produce(self, topic, key, value, on_delivery):
        """
        A produce method in which delivery notifications are made available
        via both the returned future and on_delivery callback (if specified).
        """
        result = self._loop.create_future()

        def ack(err, msg):
            if err:
                self._loop.call_soon_threadsafe(
                    result.set_exception, KafkaException(err))
            else:
                self._loop.call_soon_threadsafe(
                    result.set_result, msg)
            if on_delivery:
                self._loop.call_soon_threadsafe(
                    on_delivery, err, msg)

        self._producer.produce(topic=topic, key=key, value=value, on_delivery=ack)
        self._producer.flush()
        return result
```

Proto file:
```
syntax = "proto2";

message Meal {
  required string name = 1;
  optional string alternate_name = 2;

  enum FoodType {
    INGREDIENT = 0;
    FILLING = 1;
    TOPPING = 2;
  }

  enum DrinkType {
    BUBBLY = 0;
    ALCOHOLIC = 1;
  }

  message MealItems {
    required string item_name = 1;
    optional FoodType type = 2 [default = INGREDIENT];
  }

  message DrinkItems {
    required string drink_name = 1;
    optional DrinkType type = 2 ;
  }

  repeated MealItems item = 4;
  repeated DrinkItems drink = 5;
}
```

Checklist
=========
Please provide the following information:

 - [x] confluent-kafka-python and librdkafka version (`confluent_kafka.version()` and `confluent_kafka.libversion()`):1.6.1
 - [x] Apache Kafka broker version: 2.7.0 (Commit:448719dc99a19793)
 - [x] Client configuration: 
 
 ```
bootstrap.servers=localhost:9092
schema.registry.url=http://localhost:8081/api/ccompat
cdc.input.topic=pbf-meal
group.id=pbf-meal 
```

 - [x] Operating system:macos big sur
 - [x] Provide client logs (with `'debug': '..'` as necessary)
 ```

Traceback (most recent call last):
  File "/opt/anaconda3/envs/fast_ksql_ccloud/lib/python3.8/site-packages/confluent_kafka/serializing_producer.py", line 172, in produce
    value = self._value_serializer(value, ctx)
  File "/opt/anaconda3/envs/fast_ksql_ccloud/lib/python3.8/site-packages/confluent_kafka/schema_registry/protobuf.py", line 320, in __call__
    self._schema_id = self._registry.register_schema(subject,
  File "/opt/anaconda3/envs/fast_ksql_ccloud/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 336, in register_schema
    response = self._rest_client.post(
  File "/opt/anaconda3/envs/fast_ksql_ccloud/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 127, in post
    return self.send_request(url, method='POST', body=body)
  File "/opt/anaconda3/envs/fast_ksql_ccloud/lib/python3.8/site-packages/confluent_kafka/schema_registry/schema_registry_client.py", line 174, in send_request
    raise SchemaRegistryError(response.status_code,
confluent_kafka.schema_registry.error.SchemaRegistryError: RESTEASY003210: Could not find resource for full path: http://localhost:8081/apis/registry/v1/ccompat/subjects/pbf-meal-value/versions (HTTP status code 404, SR code 404)

```
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by EricWittmann** [comment]
I suspect you're using the wrong API endpoint for the Confluent compatibility REST API.  Try this endpoint:

`http://localhost:8081/apis/ccompat/v6`

My guess is you're using the old endpoint of `/api/ccompat` which is being rewritten as `/apis/registry/v1/ccompat`.  Unfortunately that won't work and you'll need to use the endpoint above.

**Comment by Akhilj786** [comment]
@EricWittmann Yes changing the endpoint fixed it. Thanks.
