### ISSUE TITLE
`DataException: Invalid type for INT64: class java.lang.Integer` on `connect.default` for int64 Avro type

### ISSUE THREAD

**Issue by drnushooz** [Apicurio/apicurio-registry#1740]
There is an issue with Avro 1.9+ where if a field of type long has connect.default property, e.g.
```
"type": "record"
"name": "sample"
"namespace": "io.apicurio",
"fields": [
  {
    "name": "prop",
    "type": {
      "type": "long",
      "connect.default": 42,
      "connect.version": 1
    }
  }
]
```
then AvroData.toConnectSchema throws
```
org.apache.kafka.connect.errors.DataException: Invalid type for INT64: class java.lang.Integer
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1498)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1230)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1478)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1230)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1226)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1205)
	at com.github.drnushooz.kafka.connect.sqs.source.SqsSourceTask.lambda$poll$0(SqsSourceTask.java:138)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.drnushooz.kafka.connect.sqs.source.SqsSourceTask.poll(SqsSourceTask.java:149)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:265)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:232)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by drnushooz** [comment]
@EricWittmann would it be possible to triage this and get it prioritized? This is hindering some functionality on our side.

**Comment by carlesarnal** [comment]
Hi @drnushooz, Eric's on PTO, I'll take a look at the linked PR.

**Comment by drnushooz** [comment]
> Hi @drnushooz, Eric is on PTO, I'll take a look at the linked PR.

Thank you.

**Comment by drnushooz** [comment]
> Hi @drnushooz, Eric is on PTO, I'll take a look at the linked PR.

Is there a tentative schedule for the next maintenance release?

**Comment by EricWittmann** [comment]
Our next upstream release will be 2.1.0.  We'll be able to release that soon.  Perhaps as early as Friday of this week.

**Comment by EricWittmann** [comment]
Didn't get a chance to plan and execute the release today - I am optimistic it can be done Monday.

**Comment by EricWittmann** [comment]
OK we've done a release of 2.1.0.RC1 - this is a release candidate.  We would very much appreciate it if interested parties could give it a try and give us your feedback.

**Comment by drnushooz** [comment]
Thanks, I will pull this release into our staging environment and test it.

**Comment by EricWittmann** [comment]
I will be **very** interested in your experience, since this is a minor release with some non-trivial changes.  Nothing should be breaking, but we may have messed up somewhere along the way.  Please report back with any issues and we'll get them fixed before `2.1.0.Final`.

**Comment by HelloSunilSaini** [comment]
io.apicurio.apicurio-registry-distro-connect-converter 2.0.0-SNAPSHOT this package is the letast one [here](https://github.com/Apicurio/apicurio-registry/packages/599443)

**Comment by drnushooz** [comment]
@HelloSunilSaini you can find the latest version of the connector on Manven Central https://mvnrepository.com/artifact/io.apicurio/apicurio-registry-distro-connect-converter/2.3.1.Final
