### ISSUE TITLE
Schema registry failure with artifactId having '-'

### ISSUE THREAD

**Issue by KasturiHima** [Apicurio/apicurio-registry#1741]
If we have '-' in the artifactId of the schema registry then we are getting below error message 
Example: we created schema with artifactId "net-velocity" and tried to consume messages using this artifactId But we are getting the below error.If we replace the artifactId with "netvelocity" we are able to consume the messages.

**Error:**
```
Exception in thread "main" org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition net-velocity-0 at offset 0. If needed, please seek past the record to continue consumption.
Caused by: java.lang.RuntimeException: ArtifactId not found in headers.
        at io.apicurio.registry.utils.serde.JsonSchemaKafkaDeserializer.getArtifactId(JsonSchemaKafkaDeserializer.java:114)
        at io.apicurio.registry.utils.serde.JsonSchemaKafkaDeserializer.deserialize(JsonSchemaKafkaDeserializer.java:76)
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1387)
        at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1618)
        at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1454)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:687)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:638)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1299)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1233)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1206)
        at databus_apicurio_testing.examples.NetVelocityCloudEventJsonSchemaExample.main(NetVelocityCloudEventJsonSchemaExample.java:141)
```

**Below is the consumer code:**

```java
        KafkaConsumer<Long, CloudEventBean> consumer = createKafkaConsumer(args[0],args[1],args[2]);

        System.out.println("Subscribing to topic " + topicName);
        consumer.subscribe(Collections.singletonList(topicName));

        // Consume the 5 messages.
        try {
            int messageCount = 0;
            System.out.println("Consuming (5) messages.");
            while (messageCount < 5) {
                final ConsumerRecords<Long, CloudEventBean> records = consumer.poll(Duration.ofSeconds(1));
                messageCount += records.count();
                if (records.count() == 0) {
                    // Do nothing - no messages waiting.
                    System.out.println("No messages waiting...");
                } else records.forEach(record -> {
                		CloudEventBean msg = record.value();
                		System.out.println("Consumed a message: " + msg.getSource());
                });
            }
        } finally {
            consumer.close();
        }

        System.out.println("Done (success).");
```

**Comment by KasturiHima** [comment]
someone please help on this issue.

**Comment by carlesarnal** [comment]
Hi, @KasturiHima if you can provide a small reproducer that would help a lot.

**Comment by carlesarnal** [comment]
Also, which version of registry are you using? Your log suggests that you're using an old version of the application.

**Comment by EricWittmann** [comment]
@KasturiHima what version of registry are you using?  Version 2.0 has been significantly updated in the Serdes area.  The stack trace provided doesn't make sense for 2.0 so I'm guessing you're using an older version?

**Comment by KasturiHima** [comment]
> Also, which version of registry are you using? Your log suggests that you're using an old version of the application.

we are using version 2.0

**Comment by carlesarnal** [comment]
Could you please double check that you’re also using serdes 2.0? The stacktrace contains classes from older versions

**Comment by carlesarnal** [comment]
Closing as stale. If someone face this in the future please, re-open.
