### ISSUE TITLE
Unsupported operation in OIDC http client

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#1796]
When running the registry in multi-tenant mode, the tenant manager client fails when not properly configured.  That part is fine, but it fails with an `UnsupportedOperationException`.

```
2021-08-242 11:18:11 ERROR <> [io.apicurio.registry.mt.TenantReaper] (executor-thread-1) Exception thrown when running tenant reaper job: java.lang.UnsupportedOperationException
	at io.apicurio.rest.client.auth.exception.AuthErrorHandler.parseError(AuthErrorHandler.java:29)
	at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:192)
	at io.apicurio.rest.client.auth.OidcAuth.requestAccessToken(OidcAuth.java:118)
	at io.apicurio.rest.client.auth.OidcAuth.apply(OidcAuth.java:106)
	at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:162)
	at io.apicurio.multitenant.client.TenantManagerClientImpl.listTenants(TenantManagerClientImpl.java:110)
	at io.apicurio.registry.mt.TenantReaper.reap(TenantReaper.java:133)
	at io.apicurio.registry.mt.TenantReaper_Subclass.reap$$superaccessor1(TenantReaper_Subclass.zig:237)
	at io.apicurio.registry.mt.TenantReaper_Subclass$$function$$1.apply(TenantReaper_Subclass$$function$$1.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.mt.TenantReaper_Subclass.reap(TenantReaper_Subclass.zig:195)
	at io.apicurio.registry.mt.TenantReaper.run(TenantReaper.java:105)
	at io.apicurio.registry.mt.TenantReaper_Subclass.run$$superaccessor2(TenantReaper_Subclass.zig:344)
	at io.apicurio.registry.mt.TenantReaper_Subclass$$function$$2.apply(TenantReaper_Subclass$$function$$2.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.mt.TenantReaper_Subclass.run(TenantReaper_Subclass.zig:302)
	at io.apicurio.registry.mt.TenantReaper_ClientProxy.run(TenantReaper_ClientProxy.zig:126)
	at io.apicurio.registry.mt.TenantReaper_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invokeBean(TenantReaper_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.zig:46)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
	at io.quarkus.scheduler.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:19)
	at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.run(SimpleScheduler.java:204)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

In this case, the root error is this:

```
java.net.ConnectException: Connection refused: no further information
```

But it seems to me that there is an unhandled path, since we should never throw `UnsupportedOperationException` even under a mis-configuration... IMO.

**Comment by carlesarnal** [comment]
I used the `UnsupportedOperationException` because all the auth related errors in the AuthErrorHandler should be processed using a different method. Possibly not the best choice...

**Comment by carlesarnal** [comment]
This can be close now.
