### ISSUE TITLE
Type coercion based on schema data type rather than value for INT64

### ISSUE THREAD

**Issue by drnushooz** [Apicurio/apicurio-registry#1825]
I have been experimenting with the 2.1.0.RC1 release and noticed an issue with Avro to Connect data conversion. We have a use case to convert JSON data with `long` values in the payload. This data gets received by Kafka and we use Talend's [Diakon](https://github.com/Talend/daikon) library to infer the schema dynamically. Diakon uses Jackson internally to deserialize JSON. Some of the attributes in the JSON body don't have values large enough and automatic schema inference treats them as `int` rather than `long` which isn't desired. To handle this, we enable `DeserializationFeature.USE_LONG_FOR_INTS` which works perfectly.

The issue arises when we try to convert this data from Avro to Connect using `AvroData#toConnectData`. Even though the schema indicates that the data is `INT64`, because the value is small and can fit into an `Integer`, the method throws a data exception with the following stack trace.
```
org.apache.kafka.connect.errors.DataException: Invalid type for INT64: class java.lang.Integer

	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1504)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1231)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1484)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1231)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1227)
	at io.apicurio.registry.utils.converter.avro.AvroData.toConnectData(AvroData.java:1206)
	at io.apicurio.registry.utils.converter.avro.AvroDataTest.testAvroInt64WithInteger(AvroDataTest.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at 
...

```

Here is a unit test which can reproduce this error.
```
        final String s = "{"
            + "  \"type\": \"record\","
            + "  \"name\": \"sample\","
            + "  \"namespace\": \"io.apicurio\","
            + "  \"fields\": ["
            + "    {"
            + "      \"name\": \"someprop\","
            + "      \"type\": [\"long\",\"null\"]"
            + "    }"
            + "  ]"
            + "}";

        org.apache.avro.Schema avroSchema = new org.apache.avro.Schema.Parser().parse(s);
        GenericRecord outputRecord = new GenericRecordBuilder(avroSchema).set("someprop", 42).build();
        AvroData avroData = new AvroData(0);
        SchemaAndValue connectSchemaAndData = avroData.toConnectData(avroSchema, outputRecord);
        Assertions.assertNotNull(connectSchemaAndData);
```
The solution is to check the Avro schema type and if it is an `INT64` check and convert `Integer` to a `Long` appropriately.

**Comment by drnushooz** [comment]
@carlesarnal @EricWittmann Can someone please take a look at this? It possible, I'd like to get this into 2.1.0. Thanks!

**Comment by drnushooz** [comment]
Thank you for taking in the fix. You all rock :) 👍

**Comment by drnushooz** [comment]
@EricWittmann Is there an ETA for RC2 for 2.1.0? I would like to take it for a spin.
