### ISSUE TITLE
The KafkaSql storage throws exception when querying contentIdFromHash: `Expected one element, but found none`

### ISSUE THREAD

**Issue by JoshVee** [Apicurio/apicurio-registry#1873]
```
2021-09-23 23:02:46,867 ERROR [io.api.reg.res.RegistryExceptionMapper] (kafka-producer-network-thread | Producer-e4d6384d-8790-4f37-9389-12984223a60e) java.lang.IllegalStateException: Expected one element, but found none: io.apicurio.registry.storage.RegistryStorageException: java.lang.IllegalStateException: Expected one element, but found none
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.withHandle(AbstractSqlRegistryStorage.java:171)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.withHandle$$superaccessor99(KafkaSqlStore_Subclass.zig:19833)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass$$function$$99.apply(KafkaSqlStore_Subclass$$function$$99.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
	at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:275)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.withHandle(KafkaSqlStore_Subclass.zig:19791)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.contentIdFromHash(KafkaSqlStore.java:147)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.createArtifactWithMetadata(KafkaSqlStore.java:114)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.createArtifactWithMetadata$$superaccessor139(KafkaSqlStore_Subclass.zig:24974)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass$$function$$139.apply(KafkaSqlStore_Subclass$$function$$139.zig:83)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
	at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:275)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.createArtifactWithMetadata(KafkaSqlStore_Subclass.zig:24897)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_ClientProxy.createArtifactWithMetadata(KafkaSqlStore_ClientProxy.zig:2381)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processArtifactMessage(KafkaSqlSink.java:227)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.doProcessMessage(KafkaSqlSink.java:139)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processMessage(KafkaSqlSink.java:94)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage$$superaccessor6(KafkaSqlSink_Subclass.zig:1146)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass$$function$$6.apply(KafkaSqlSink_Subclass$$function$$6.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
	at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:275)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage(KafkaSqlSink_Subclass.zig:1103)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_ClientProxy.processMessage(KafkaSqlSink_ClientProxy.zig:128)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$1(KafkaSqlRegistryStorage.java:293)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$2(KafkaSqlRegistryStorage.java:267)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalStateException: Expected one element, but found none
	at org.jdbi.v3.core.result.ResultIterable.one(ResultIterable.java:135)
	at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.lambda$contentIdFromHash$6(KafkaSqlStore.java:152)
	at org.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:342)
	at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.withHandle(AbstractSqlRegistryStorage.java:167)
	... 46 more
```

**Comment by EricWittmann** [comment]
Do you have any other context to this?  Any steps to reproduce?  Or does it just always happen for you?  This looks like it's trying to create an artifact, right?  How did you create the artifact?  UI?  SerDes?   API?  Maven plugin?  Any other information you can provide would be helpful.

**Comment by JoshVee** [comment]
> Do you have any other context to this? Any steps to reproduce? Or does it just always happen for you? This looks like it's trying to create an artifact, right? How did you create the artifact? UI? SerDes? API? Maven plugin? Any other information you can provide would be helpful.

Hi @EricWittmann. The schemas were being created directly by the Producer, via the Apicurio Converter.

**Comment by mdharper** [comment]
Something definitely changed. Here's what I got on startup -- a lot of the "Discarded a (presumed) tombstone message" messages followed by a number of primary key violations. When everything loaded, the registry appeared to be empty.
```

2021-10-286 19:58:29 INFO <> [io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage] (KSQL Kafka Consumer Thread) Discarded a (presumed) tombstone message with key: ArtifactRuleKey [groupId=null, artifactId=_SAMPLE_SCHEMA, ruleType=COMPATIBILITY]
2021-10-286 19:58:29 WARN <> [io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage] (KSQL Kafka Consumer Thread) Failed to import content entity.: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "UNQ_CONTENT_1_INDEX_6 ON PUBLIC.CONTENT(CONTENTHASH) VALUES ('5c023991ed42779802181e940d9653912621600dcd92cf8f8f3fdecfb5f83df5', 21)"; SQL statement:
INSERT INTO content (contentId, canonicalHash, contentHash, content) VALUES (?, ?, ?, ?) [23505-197]
        at io.apicurio.registry.storage.impl.sql.jdb.UpdateImpl.execute(UpdateImpl.java:46)
        at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.importContent(AbstractSqlRegistryStorage.java:2674)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.lambda$importContent$10(KafkaSqlStore.java:192)
        at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandle(HandleFactory.java:44)
        at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandleNoException(HandleFactory.java:52)
        at io.apicurio.registry.storage.impl.sql.HandleFactory_ClientProxy.withHandleNoException(HandleFactory_ClientProxy.zig:190)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore.importContent(KafkaSqlStore.java:191)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.importContent$$superforward1(KafkaSqlStore_Subclass.zig:10543)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass$$function$$171.apply(KafkaSqlStore_Subclass$$function$$171.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
        at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:327)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_Subclass.importContent(KafkaSqlStore_Subclass.zig:29540)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlStore_ClientProxy.importContent(KafkaSqlStore_ClientProxy.zig:3605)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processContent(KafkaSqlSink.java:372)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.doProcessMessage(KafkaSqlSink.java:158)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink.processMessage(KafkaSqlSink.java:104)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage$$superforward1(KafkaSqlSink_Subclass.zig:768)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass$$function$$15.apply(KafkaSqlSink_Subclass$$function$$15.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.apicurio.registry.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:55)
        at io.apicurio.registry.logging.LoggingInterceptor_Bean.intercept(LoggingInterceptor_Bean.zig:327)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_Subclass.processMessage(KafkaSqlSink_Subclass.zig:2189)
        at io.apicurio.registry.storage.impl.kafkasql.sql.KafkaSqlSink_ClientProxy.processMessage(KafkaSqlSink_ClientProxy.zig:128)
        at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$1(KafkaSqlRegistryStorage.java:282)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.apicurio.registry.storage.impl.kafkasql.KafkaSqlRegistryStorage.lambda$startConsumerThread$2(KafkaSqlRegistryStorage.java:256)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by EricWittmann** [comment]
The test passes:  https://github.com/Apicurio/apicurio-registry/pull/1955

@mdharper how many instances of the registry are you running?  Just one, or multiple?

**Comment by EricWittmann** [comment]
We think this might be a log compaction issue.  I think some of our kafka messages do not have correct keys compatible with our intended use of log compaction.  We've tried to be rather deliberate on this point but I think we got a couple of our message keys wrong.  Still evaluating.
