### ISSUE TITLE
Apicurio schema registry with JsonSchemaKafkaSerializer and JsonSchemaKafkaDeserializer not working

### ISSUE THREAD

**Issue by nehasewda** [Apicurio/apicurio-registry#1879]
I am trying to implement schema registry using kafka streams with JSON serde(Input data is in JSON format). But unable to do so, It's not even throwing any error when I am publishing data in the input kafka topic. 
After debugging little more, I found that only the serializer and deserializer(serde) part is causing this issue as the same code is working with primitive serde like String, Integer.

Here is the logic - 

Properties set are - 
```java
properties.put(AbstractKafkaSerDe.REGISTRY_URL_CONFIG_PARAM,schemaRegUrl);
properties.put(AbstractKafkaSerializer.REGISTRY_ARTIFACT_ID_STRATEGY_CONFIG_PARAM, SimpleTopicIdStrategy.class.getName());
 properties.put(AbstractKafkaSerializer.REGISTRY_GLOBAL_ID_STRATEGY_CONFIG_PARAM, GetOrCreateIdStrategy.class.getName());
properties.put(JsonSchemaSerDeConstants.REGISTRY_JSON_SCHEMA_VALIDATION_ENABLED, Boolean.TRUE);

RegistryService service = CompatibleClient.createCompatible(schemaRegUrl);
Serializer<POJO> serializer = new JsonSchemaKafkaSerializer<>(service, true);
Deserializer<POJO> deserializer = new JsonSchemaKafkaDeserializer<>(service, true);
Serde<DataModel> logSerde = Serdes.serdeFrom(serializer, deserializer);

StreamsBuilder builder = new StreamsBuilder();
KStream<String, POJO> input = builder.stream(INPUT_TOPIC, Consumed.with(stringSerde, logSerde));
```

Not sure what's missing in the above code as I am not receiving any error while running.
Kindly help.

**Comment by EricWittmann** [comment]
So one thing that jumps out at me in the code snippet above is that you're not using the `properties` anywhere.

Another thing is that I understand that you're not seeing any errors, but is it just not doing anything at all?  Or is it doing something you didn't expect?  If you put a breakpoint in the `JsonSchemaKafkaSerializer` or `JsonSchemaKafkaDeserializer` classes do they ever get hit?  (in their respective `serializer` or `deserialize` methods)

Finally, this appears to be Apicurio Registry v1 SerDes classes.  If you are able to use v2 of Registry that would definitely be better.  The latest release is 2.1.0.Final.

**Comment by EricWittmann** [comment]
@famartinrh any additional thoughts on this?

**Comment by famartinrh** [comment]
I completely agree with the points Eric made. Also I would encourage @nehasewda to migrate to the latest version of Apicurio Registry

**Comment by nehasewda** [comment]
Hi @EricWittmann ,

I am using the suggested version of Serde classes but still getting the below issue-

**Caused by: java.lang.IllegalStateException: artifactId cannot be null**
at io.apicurio.registry.serde.DefaultSchemaResolver.resolveSchemaByCoordinates(DefaultSchemaResolver.java:122)
at io.apicurio.registry.serde.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:114)
at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:150)
at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:135)
at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:130)
at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:58)
at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66)


Here is the complete code - 

Properties properties = new Properties();
properties.put(StreamsConfig.BOOTSTRAP_SERVERS_CONFIG, kafkabroker);
properties.put(StreamsConfig.APPLICATION_ID_CONFIG, "registry-demo");
RegistryClient rs = RegistryClientFactory.create(schemaRegUrl);
StreamsBuilder builder = new StreamsBuilder();

Serializer<DataModel> serializer = new io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaSerializer<DataModel>(rs, true);
Deserializer<DataModel> deserializer = new io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaDeserializer<DataModel>(rs);
Map < String, Object > serdeProps = new HashMap < > ();
serdeProps.put(SerdeConfig.REGISTRY_URL, schemaReg);
serdeProps.put(SerdeConfig.ARTIFACT_RESOLVER_STRATEGY, io.apicurio.registry.serde.strategy.SimpleTopicIdStrategy.class.getName());
serdeProps.put(SerdeConfig.VALIDATION_ENABLED, true);
serdeProps.put(AbstractKafkaSerializer.REGISTRY_ARTIFACT_ID_STRATEGY_CONFIG_PARAM, SimpleTopicIdStrategy.class.getName());

Map < String, Object > serdePropsDs = new HashMap < > ();
 serdePropsDs.put(SerdeConfig.REGISTRY_URL, schemaReg);

serializer.configure(serdeProps, false);
deserializer1.configure(serdePropsDs, false);
 Serde<DataModel> logSerde = Serdes.serdeFrom(serializer, deserializer);

KStream<String, DataModel> input = builder.stream(INPUT_TOPIC,Consumed.with(Serdes.String(),logSerde));
input.to(outputTopic, Produced.with(Serdes.String(), logSerde));

Topology topology = builder.build(properties);
 topology.describe();
 streams = new KafkaStreams(topology, properties);
 streams.start();



For Json serde classes latest version is being used.
**I have created an artifact via apicurio UI with the same name as the INPUT_TOPIC but still getting the above error.**
Please confirm if any changes are required in the code.

**Comment by famartinrh** [comment]
First one minor thing, looks like you have the 1.3.x old version and the 2.x new version of our serdes libraries available in your classpath. The propety comes from the old version of the library. To avoid issues and confusion, please remove the 1.3.x apicurio serdes dependency from your app.

Now about your issue, I think there is a misunderstandment here on how our serializers and deserializers work. 
I see you are reading directly from the INPUT_TOPIC using our Deserializer...

The way our SerDes work is: first the Serializer writes some identifier of the schema being used along the kafka message. then after that happens, using the before mentioned identifier, the Deserializer is able to fetch from the registry the schema.

So in order for your application to work you need to first produce messages to kafka using our Serializers and then our Deserializers will be able to successfully read the messages.

**Comment by nehasewda** [comment]
Thanks @famartinrh for the response.

As per my understanding in the above code, I am creating a Json serde(logserde) from JsonSchemaKafkaSerializer and JsonSchemaKafkaDeserializer classes. Consumed.with() and Produced.with() method are used for kafka streams to serialize and deserialize the data records in INPUT_TOPIC and OUTPUT_TOPIC.

Therefore when you say that I need to first produce the messages to kafka using serializer, what exactly do you mean by that as kafka streams uses Serde instead of seperate serializer and deserializer?

**Comment by famartinrh** [comment]
I mean that your stream is like
```
KStream<String, DataModel> input = builder.stream(INPUT_TOPIC,Consumed.with(Serdes.String(),logSerde));
input.to(outputTopic, Produced.with(Serdes.String(), logSerde));
```
and my point is, the messages sent to INPUT_TOPIC are not serialized by Apicurio SerDes

i.e. take a look at this example application
The stream starts from `orders` topic
https://github.com/Apicurio/apicurio-registry-examples/blob/master/quarkus-demo/quarkus-kafka-streams/src/main/java/io/apicurio/example/kstreams/KStreamsTopologyProducer.java
The messages sent to `orders` topic come from here using `io.apicurio.registry.serde.avro.AvroKafkaSerializer` 
https://github.com/Apicurio/apicurio-registry-examples/blob/master/quarkus-demo/quarkus-kafka-streams/src/main/java/io/apicurio/example/orders/OrdersResource.java
https://github.com/Apicurio/apicurio-registry-examples/blob/master/quarkus-demo/quarkus-kafka-streams/src/main/resources/application.yaml#L24

**Comment by nehasewda** [comment]
Hi @famartinrh ,

As per your suggestion, I have published the message using apicurio serializer given as below - 

### Producer code - 

Properties props = new Properties();
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, serviceKafka);
props.put(ProducerConfig.CLIENT_ID_CONFIG, "KafkaProducerExample");
props.put("apicurio.registry.url", schemaRegUrl);
props.put("apicurio.registry.headers.enabled", true);
props.put("apicurio.registry.artifact-resolver-strategy",io.apicurio.registry.serde.strategy.SimpleTopicIdStrategy.class);
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaSerializer.class);
KafkaProducer<String, DataModel> kp = new KafkaProducer(props);
DataModel d = new DataModel("a","test");
final ProducerRecord<String, DataModel> record = new ProducerRecord(INPUT_TOPIC, "key1", d);
kp.send(record, (metadata, exception)->{
    if(metadata != null){
        System.out.println(metadata.toString());
    }else{
        exception.printStackTrace();
    }
});

But I am still getting the same error.

**NOTE - kafka consumer app is able to validate the messages using apicurio registry but not kafka streams.**

### Consumer code - 

Properties propConsume = new Properties();
propConsume.put(ConsumerConfig.BOOTSTRAP_SERVERS_CONFIG, serviceKafka);
propConsume.put(ConsumerConfig.GROUP_ID_CONFIG, "KafkaConsumerExample");
propConsume.put("apicurio.registry.url", schemaReg);
propConsume.put("apicurio.registry.artifact-resolver-strategy",io.apicurio.registry.serde.strategy.SimpleTopicIdStrategy.class);
propConsume.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
propConsume.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaDeserializer.class);
Consumer<String, DataModel> consumer = new KafkaConsumer<>(propConsume);
consumer.subscribe(Collections.singleton(inputTopic));
ConsumerRecords<String, DataModel> recordCon = consumer.poll(1000);

**Comment by famartinrh** [comment]
if a simple kafka consumer configured with our Deserializer can read the message, a kafka streams app should read it as well. Try to revisit your configuration in the kafka streams app to match the consumer that works.

Also if you want to publish your app in GitHub or something to provide a reproducer app, I could review it

**Comment by nehasewda** [comment]
@famartinrh,
Here's the git repo - https://github.com/nehasewda/streams-demo
Could you please review.

**Comment by nehasewda** [comment]
Hi @famartinrh,

Did you get a chance to review the above code.

**Comment by famartinrh** [comment]
Hi, yes, you don't have any json schema, our SerDes for json require a json schema to be registered beforehand. Check our our docs on how to create an artifact in Apicurio Registry.

**Comment by nehasewda** [comment]
Thanks for the review.

I have already registered a json schema via Apicurio UI with same name as the kafka topic.
Here is the schema - 
{
	"$id": "https://example.com/message.schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"required": [
		"ID",
		"Equipment"
	],
	"type": "object",
	"properties": {
		"ID": {
			"description": "",
			"type": "string"
		},
		"Equipment": {
			"description": "",
			"type": "string"
		}
	}
}

NOTE - The Kafka Producer and Consumer APIs are able to validate the records with the schema from registry.

**Comment by famartinrh** [comment]
I'm glad it finally worked for you

**Comment by nehasewda** [comment]
Hi @EricWittmann ,
Thanks for reopening the issue.

Could you please check the problem with my kafka streams code - https://github.com/nehasewda/streams-demo
Here, **the code is working all fine with Kafka Producer and Consumer APIs but not with Kafka streams**.

I got some help from @famartinrh but the issue still exists.
Kindly help.

**Comment by EricWittmann** [comment]
OK I've just spent some time on this.  I got your demo app working.  There are a few thing to mention.

First, I needed to remove the `required` section of your schema otherwise validation was failing.  I'm not sure why that was, and I don't have a lot of time to figure that part out.  It could be a bug in the JSON Schema validator library we're using.  That part requires some investigation perhaps.

Here is a gist of the demo application with my changes:

https://gist.github.com/EricWittmann/ac57bd3b2e680850a08d27caa5ef3c08

Also I added a comment with the output I get.

Note that one big mistake I noticed was right at the end here:

https://github.com/nehasewda/streams-demo/blob/master/src/main/java/KafkaStreamsExample.java#L126

The `start()` method starts the threads in the background.  If you immediately fall out the end of your `main` method, the streams application won't do anything, because it will start up the background threads for the Kafka Stream and then immediately quit the java application.

That's why I added the `Thread.sleep(5000)` at the end - to give the stream time to process the messages in the topic, before closing the KafkaStream and quitting the app.

**Comment by nehasewda** [comment]
@EricWittmann 

Thank you so very much for the help. It's working fine now.
