### ISSUE TITLE
fix clustered kafkasql integration tests 

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry#2080]
```
2021-12-02T20:42:08.8348811Z 2021-12-02T20:41:35.079Z INFO  [TestSeparator] ############################################################################
2021-12-02T20:42:08.8350818Z 2021-12-02T20:41:35.083Z INFO  [TestSeparator] io.apicurio.tests.converters.RegistryConverterIT.testCompactJson-STARTED
2021-12-02T20:42:08.8359349Z 2021-12-02T20:41:35.126Z INFO  [JsonConverterConfig] JsonConverterConfig values: 
2021-12-02T20:42:08.8360273Z 	converter.type = value
2021-12-02T20:42:08.8360896Z 	schemas.cache.size = 1000
2021-12-02T20:42:08.8361534Z 	schemas.enable = false
2021-12-02T20:42:08.8361977Z 
2021-12-02T20:42:08.8362845Z 2021-12-02T20:42:05.445Z INFO  [RegistryConverterIT] Removing all artifacts
2021-12-02T20:42:08.8365336Z 2021-12-02T20:42:05.580Z INFO  [TestSeparator] io.apicurio.tests.converters.RegistryConverterIT.testCompactJson-FINISHED
2021-12-02T20:42:08.8396208Z 2021-12-02T20:42:05.580Z INFO  [TestSeparator] ############################################################################
2021-12-02T20:42:08.8511729Z 2021-12-02T20:42:05.582Z ERROR [RegistryDeploymentManager] Test failed with error:
2021-12-02T20:42:08.8516215Z io.apicurio.registry.rest.client.exception.RestClientException: Cannot invoke "java.lang.Long.longValue()" because the return value of "io.apicurio.registry.storage.impl.kafkasql.KafkaSqlCoordinator.waitForResponse(java.util.UUID)" is null
2021-12-02T20:42:08.8522163Z 	at io.apicurio.registry.rest.client.impl.ErrorHandler.handleErrorResponse(ErrorHandler.java:63)
2021-12-02T20:42:08.8524687Z 	at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:46)
2021-12-02T20:42:08.8526340Z 	at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:193)
2021-12-02T20:42:08.8552869Z 	at io.apicurio.registry.rest.client.impl.RegistryClientImpl.createArtifact(RegistryClientImpl.java:236)
2021-12-02T20:42:08.8555610Z 	at io.apicurio.registry.rest.client.RegistryClient.createArtifact(RegistryClient.java:138)
2021-12-02T20:42:08.8558019Z 	at io.apicurio.registry.serde.DefaultSchemaResolver.lambda$handleAutoCreateArtifact$2(DefaultSchemaResolver.java:174)
2021-12-02T20:42:08.8559942Z 	at io.apicurio.registry.serde.ERCache.lambda$getValue$0(ERCache.java:132)
2021-12-02T20:42:08.8561225Z 	at io.apicurio.registry.serde.ERCache.retry(ERCache.java:171)
2021-12-02T20:42:08.8562527Z 	at io.apicurio.registry.serde.ERCache.getValue(ERCache.java:131)
2021-12-02T20:42:08.8564702Z 	at io.apicurio.registry.serde.ERCache.getByContent(ERCache.java:116)
2021-12-02T20:42:08.8567010Z 	at io.apicurio.registry.serde.DefaultSchemaResolver.handleAutoCreateArtifact(DefaultSchemaResolver.java:172)
2021-12-02T20:42:08.8569919Z 	at io.apicurio.registry.serde.DefaultSchemaResolver.resolveSchema(DefaultSchemaResolver.java:82)
2021-12-02T20:42:08.8572633Z 	at io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(ExtJsonConverter.java:97)
2021-12-02T20:42:08.8577086Z 	at io.apicurio.registry.utils.converter.ExtJsonConverter.fromConnectData(ExtJsonConverter.java:83)
2021-12-02T20:42:08.8580254Z 	at apicurio.registry.integration.tests.testsuite@2.1.4-SNAPSHOT/io.apicurio.tests.converters.RegistryConverterIT.testJson(RegistryConverterIT.java:170)
2021-12-02T20:42:08.8583827Z 	at apicurio.registry.integration.tests.testsuite@2.1.4-SNAPSHOT/io.apicurio.tests.converters.RegistryConverterIT.testCompactJson(RegistryConverterIT.java:147)
2021-12-02T20:42:08.8586511Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-12-02T20:42:08.8588410Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2021-12-02T20:42:08.8590688Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-12-02T20:42:08.8592329Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2021-12-02T20:42:08.8593812Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
2021-12-02T20:42:08.8595836Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2021-12-02T20:42:08.8598269Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2021-12-02T20:42:08.8600733Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2021-12-02T20:42:08.8603225Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2021-12-02T20:42:08.8608520Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2021-12-02T20:42:08.8611939Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2021-12-02T20:42:08.8615888Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-12-02T20:42:08.8618379Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-12-02T20:42:08.8627203Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2021-12-02T20:42:08.8630396Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2021-12-02T20:42:08.8633622Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2021-12-02T20:42:08.8637940Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2021-12-02T20:42:08.8640007Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2021-12-02T20:42:08.8642498Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
2021-12-02T20:42:08.8645552Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8648578Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
2021-12-02T20:42:08.8654240Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
2021-12-02T20:42:08.8656950Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
2021-12-02T20:42:08.8659583Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-12-02T20:42:08.8662533Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8665196Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-12-02T20:42:08.8667492Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-12-02T20:42:08.8669615Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-12-02T20:42:08.8672273Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8675127Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-12-02T20:42:08.8677797Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-12-02T20:42:08.8679413Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2021-12-02T20:42:08.8682495Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-12-02T20:42:08.8686508Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-12-02T20:42:08.8689126Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8691774Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-12-02T20:42:08.8693938Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-12-02T20:42:08.8696057Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-12-02T20:42:08.8698668Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8701507Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-12-02T20:42:08.8704104Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-12-02T20:42:08.8705697Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2021-12-02T20:42:08.8708817Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-12-02T20:42:08.8712731Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
2021-12-02T20:42:08.8715358Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8721894Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
2021-12-02T20:42:08.8732297Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2021-12-02T20:42:08.8734450Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
2021-12-02T20:42:08.8737086Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-12-02T20:42:08.8808513Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
2021-12-02T20:42:08.8811373Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
2021-12-02T20:42:08.8815085Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-12-02T20:42:08.8819647Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-12-02T20:42:08.8839679Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-12-02T20:42:08.8843051Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
2021-12-02T20:42:08.8846049Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
2021-12-02T20:42:08.8848988Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
2021-12-02T20:42:08.8863282Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
2021-12-02T20:42:08.8866804Z 	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
2021-12-02T20:42:08.8869112Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
2021-12-02T20:42:08.8882114Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
2021-12-02T20:42:08.8884549Z 	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
2021-12-02T20:42:08.8887366Z 	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
2021-12-02T20:42:08.8890028Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2021-12-02T20:42:08.8892884Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2021-12-02T20:42:08.8895713Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2021-12-02T20:42:08.8898103Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2021-12-02T20:42:08.8900055Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2021-12-02T20:42:08.8901669Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2021-12-02T20:42:08.8903213Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2021-12-02T20:42:08.8904722Z 2021-12-02T20:42:05.583Z INFO  [RegistryFacade] Stopping registry
```

**Comment by carlesarnal** [comment]
I fixed this a while ago.
