### ISSUE TITLE
REFRESH_TOKEN_ERROR with KeyCloack Integration

### ISSUE THREAD

**Issue by claudiohs-inditex** [Apicurio/apicurio-registry#2119]
Dear all, I have installed APICurio Registry in Docker with the bellow configuration:

```

docker network create apicurio-network -o com.docker.network.bridge.enable_icc=true

docker run \
  --name docker-postgres-server \
  -p 5432:5432 \
  --net=apicurio-network  \
  -e POSTGRES_PASSWORD=1234 \
  -d postgres 

docker exec -it \
	docker-postgres-server psql \
	-U postgres \
	-c "CREATE DATABASE \"apicurio-registry-db\" ENCODING 'LATIN1' TEMPLATE template0 LC_COLLATE 'C' LC_CTYPE 'C';"

docker run  -it \
  -p 8180:8180 \
  --name docker-keycloack \
  -e KEYCLOAK_USER=admin \
  -e KEYCLOAK_PASSWORD=admin \
  -e "KEYCLOAK_LOGLEVEL=DEBUG" \
  -e "ROOT_LOGLEVEL=INFO" \
  -v /Users/cohr/Projects/APICurio:/apicurio-keycloak-config \
  -e KEYCLOAK_IMPORT=/apicurio-keycloak-config/realm-export.json \
  --net=apicurio-network  \
  quay.io/keycloak/keycloak:latest \
  -b 0.0.0.0 -Djboss.http.port=8180

docker run -it \
  -p 8080:8080 \
  -e "REGISTRY_DATASOURCE_URL=jdbc:postgresql://docker-postgres-server/apicurio-registry-db" \
  -e "REGISTRY_DATASOURCE_USERNAME=postgres" \
  -e "REGISTRY_DATASOURCE_PASSWORD=1234" \
  -e "AUTH_ENABLED=true" \
  -e "KEYCLOAK_URL=http://docker-keycloack:8180/auth/" \
  -e "KEYCLOAK_REALM=registry" \
  -e "KEYCLOAK_API_CLIENT_ID=registry-api" \
  -e "KEYCLOAK_UI_CLIENT_ID=apicurio-registry" \
  -e "ROLE_BASED_AUTHZ_ENABLED=true" \
  -e "ROLE_BASED_AUTHZ_SOURCE=token" \
  -e "REGISTRY_AUTH_ROLES_ADMIN=sr-admin" \
  -e "REGISTRY_AUTH_ROLES_DEVELOPER=sr-developer" \
  --name docker-apicurio-registry \
  --net=apicurio-network  \
  apicurio/apicurio-registry-sql:latest-release

```

Then, I access to http://localhost:8080/ui/ 
1.- If I'm not logged, I'm redirected to keycloack to enter user and pass.
2. When I'm looged, start a infinite redirect loop between apicurio registry and keycloack.

In the keycloack logs I find this Warning error:

type=REFRESH_TOKEN_ERROR, realmId=registry, clientId=apicurio-registry, userId=null, ipAddress=172.30.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret

Please, can anybody help me to fix this issue?
Thanks of lot

**Comment by EricWittmann** [comment]
@carlesarnal any thoughts?

**Comment by claudiohs-inditex** [comment]
I find a similar question here related to the infinite loop

https://johnnn.tech/q/openshift-keycloak-4-8-3-login-to-admin-console-infinite-redirect-loop/

This is my detailed log:

```
09:31:08,321 DEBUG [org.keycloak.jose.jws.DefaultTokenManager] (default task-4) Failed to decode token: org.keycloak.jose.jws.JWSInputException: java.lang.IllegalArgumentException: Parsing error
	at org.keycloak.keycloak-core@15.1.0//org.keycloak.jose.jws.JWSInput.<init>(JWSInput.java:59)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.jose.jws.DefaultTokenManager.decode(DefaultTokenManager.java:93)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.protocol.oidc.TokenManager.toRefreshToken(TokenManager.java:500)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.protocol.oidc.TokenManager.verifyRefreshToken(TokenManager.java:466)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.protocol.oidc.TokenManager.refreshAccessToken(TokenManager.java:360)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.refreshTokenGrant(TokenEndpoint.java:565)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.protocol.oidc.endpoints.TokenEndpoint.processGrantRequest(TokenEndpoint.java:201)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:546)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:435)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:396)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:365)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:150)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:110)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:141)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:104)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:440)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:358)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:245)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.resteasy-jaxrs@3.15.1.Final//org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at javax.servlet.api@2.0.0.Final//javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at org.keycloak.keycloak-wildfly-extensions@15.1.0//org.keycloak.provider.wildfly.WildFlyRequestFilter.lambda$doFilter$0(WildFlyRequestFilter.java:41)
	at org.keycloak.keycloak-services@15.1.0//org.keycloak.services.filters.AbstractRequestFilter.filter(AbstractRequestFilter.java:43)
	at org.keycloak.keycloak-wildfly-extensions@15.1.0//org.keycloak.provider.wildfly.WildFlyRequestFilter.doFilter(WildFlyRequestFilter.java:39)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
	at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
	at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
	at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Parsing error
	at org.keycloak.keycloak-core@15.1.0//org.keycloak.jose.jws.JWSInput.<init>(JWSInput.java:46)
	... 82 more

09:31:08,326 DEBUG [org.keycloak.services.resources.Cors] (default task-4) Added CORS headers to response
09:31:08,329 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-4) JtaTransactionWrapper  commit
09:31:08,329 DEBUG [org.keycloak.transaction.JtaTransactionWrapper] (default task-4) JtaTransactionWrapper end
09:31:08,330 WARN  [org.keycloak.events] (default task-4) type=REFRESH_TOKEN_ERROR, realmId=registry, clientId=apicurio-registry, userId=null, ipAddress=172.30.0.1, error=invalid_token, grant_type=refresh_token, client_auth_method=client-secret
```

**Comment by carlesarnal** [comment]
Hi,

The integration with Keycloak is well tested. This might be a regression with the latest version of Keycloak. I'll test our docker-compose distro with the latest version and see what I get. I realized now that we're using an old version of keycloak-js, so I'll update that as well.

**Comment by claudiohs-inditex** [comment]
Finally I find the error, the problem is that we can't use localhost or 127.0.0.0 ip Address (this issue may be fixed?)

This script run OK

```
function pause(){
 read -s -n 1 -p "Press any key to continue ..."
 echo ""
}

docker network rm apicurio-network 

docker network create apicurio-network -d bridge -o com.docker.network.bridge.enable_icc=true

docker run \
  --name docker-postgres-server \
  -p 5432:5432 \
  --net=apicurio-network  \
  -e POSTGRES_PASSWORD=1234 \
  -d postgres 
  
pause
  
docker exec -it \
	docker-postgres-server psql \
	-U postgres \
	-c "CREATE DATABASE \"apicurio-registry-db\" ENCODING 'LATIN1' TEMPLATE template0 LC_COLLATE 'C' LC_CTYPE 'C';"

HOSTADDRESS=$(ipconfig getifaddr en0)
echo $HOSTADDRESS
sed 's/$HOSTADDRESS/'"$HOSTADDRESS"'/g' realm-export-template.json > realm-export.json

docker run  -it \
  -p 8090:8090 \
  --name docker-keycloack \
  -e KEYCLOAK_USER=admin \
  -e KEYCLOAK_PASSWORD=admin \
  -e "KEYCLOAK_LOGLEVEL=DEBUG" \
  -e "ROOT_LOGLEVEL=INFO" \
  -e "KEYCLOAK_HOSTNAME=192.168.0.19" \
  -e "PROXY_ADDRESS_FORWARDING=true" \
  -v /Users/cohr/Projects/APICurio:/apicurio-keycloak-config \
  -e KEYCLOAK_IMPORT=/apicurio-keycloak-config/realm-export.json \
  --net=apicurio-network  \
  quay.io/keycloak/keycloak:latest \
  -b 0.0.0.0 -Djboss.http.port=8090
  
pause

docker run -it \
  -p 8080:8080 \
  -e "REGISTRY_DATASOURCE_URL=jdbc:postgresql://docker-postgres-server/apicurio-registry-db" \
  -e "REGISTRY_DATASOURCE_USERNAME=postgres" \
  -e "REGISTRY_DATASOURCE_PASSWORD=1234" \
  -e "AUTH_ENABLED=true" \
  -e "KEYCLOAK_URL=http://192.168.0.19:8090/auth" \
  -e "KEYCLOAK_REALM=registry" \
  -e "KEYCLOAK_API_CLIENT_ID=registry-api" \
  -e "KEYCLOAK_UI_CLIENT_ID=apicurio-registry" \
  -e "ROLE_BASED_AUTHZ_ENABLED=true" \
  -e "ROLE_BASED_AUTHZ_SOURCE=token" \
  -e "REGISTRY_AUTH_ROLES_ADMIN=sr-admin" \
  -e "REGISTRY_AUTH_ROLES_DEVELOPER=sr-developer" \
  -e "QUARKUS_PROFILE=prod" \
  --name docker-registry \
  --net=apicurio-network  \
  apicurio/apicurio-registry-sql:latest-release
  
docker network inspect apicurio-network 
```

**Comment by carlesarnal** [comment]
Ahh, if you check our docker-compose distro there's a note about that. https://github.com/Apicurio/apicurio-registry/tree/master/distro/docker-compose#script-based-setup

In any case, I'm glad you figured it out.
