### ISSUE TITLE
Debezium unwrap transformation failing when ExtJsonConverter used

### ISSUE THREAD

**Issue by Skivius** [Apicurio/apicurio-registry#2275]
Hi, 

I'm trying to configure cassandra sink connector from kafka topics. Data comes from Postgres with debezium CDC and stored in JSON format with external schema in Apicurio registry.

Example of value:

```
{
	"schemaId": 26,
	"payload": {
		"before": null,
		"after": {
			"type_id": 999,
			"name": "test"
		},
		"source": {
			"version": "1.7.1.Final",
			"connector": "postgresql",
			"name": "replica",
			"ts_ms": 1645001116809,
			"snapshot": "false",
			"db": "hh",
			"sequence": "[\"14802006528\",\"14802006584\"]",
			"schema": "public",
			"table": "dict_types",
			"txId": 2353096,
			"lsn": 14802006584,
			"xmin": null
		},
		"op": "c",
		"ts_ms": 1645001117769,
		"transaction": null
	}
}
```

Cassandra sink connector wants flat data there, because of mapping ("type_id=key.type_id, name=value.name"). Debezium provides unwrap transform (SMT) for extract "after" block from payload and replace message with it:

"transforms": "unwrap",
"transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",

And when I'm trying to use it alongside with:

"key.converter": "io.apicurio.registry.utils.converter.ExtJsonConverter",
"key.converter.apicurio.registry.url": "http://apicurio:8085/apis/registry/v2",
"value.converter": "io.apicurio.registry.utils.converter.ExtJsonConverter",
"value.converter.apicurio.registry.url": "http://apicurio:8085/apis/registry/v2",

I'm getting error "Only Struct objects supported for [field extraction], found: java.util.HashMap" in debezium log. Full error stack:

```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:206)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
    at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:521)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:474)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:329)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.DataException: Only Struct objects supported for [field extraction], found: java.util.HashMap
    at org.apache.kafka.connect.transforms.util.Requirements.requireStruct(Requirements.java:52)
    at org.apache.kafka.connect.transforms.util.Requirements.requireStructOrNull(Requirements.java:61)
    at org.apache.kafka.connect.transforms.ExtractField.apply(ExtractField.java:61)
    at io.debezium.transforms.ExtractNewRecordState.apply(ExtractNewRecordState.java:149)
    at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
    ... 14 more
```

Replacing transform with 
"transforms": "Extract",
"transforms.Extract.type": "org.apache.kafka.connect.transforms.ExtractField$Value",
"transforms.Extract.field": "after",
gives the same error.

Using Avro for the source and sink connectors (with io.apicurio.registry.utils.converter.AvroConverter both for key and value) is fine - no errors from debezium unwrap.

**UPD:** I'm using debezium from docker image _debezium/connect:1.7.1.Final_ and there is apicurio libs version **2.0.2** preinstalled in /kafka/external_libs/apicurio/

```
[kafka@6c6f3aaf2284 ~]$ ls -la external_libs/apicurio/
total 17772
drwxr-xr-x 2 kafka kafka    4096 Dec 14 02:39 .
drwxr-xr-x 1 kafka kafka      32 Dec 14 02:40 ..
-rw-r--r-- 1 kafka kafka   11357 Oct  7 11:13 LICENSE
-rw-r--r-- 1 kafka kafka   11504 Oct  7 11:13 README.md
-rw-r--r-- 1 kafka kafka   17536 Oct  7 11:17 annotations-13.0.jar
-rw-r--r-- 1 kafka kafka   74182 Oct  7 11:18 apicurio-registry-client-2.0.2.Final.jar
-rw-r--r-- 1 kafka kafka   93453 Oct  7 11:14 apicurio-registry-common-2.0.2.Final.jar
-rw-r--r-- 1 kafka kafka   55111 Oct  7 11:18 apicurio-registry-serde-common-2.0.2.Final.jar
-rw-r--r-- 1 kafka kafka   21302 Oct  7 11:18 apicurio-registry-serdes-avro-serde-2.0.2.Final.jar
-rw-r--r-- 1 kafka kafka   10904 Oct  7 11:18 apicurio-registry-serdes-jsonschema-serde-2.0.2.Final.jar
-rw-r--r-- 1 kafka kafka   52763 Oct  7 11:21 apicurio-registry-utils-converter-2.0.2.Final.jar
```

**Comment by carlesarnal** [comment]
Hi @Skivius, sorry for the late reply.

If you can give us a reproducer I would really appreciate it. It is a bit hard for me to reproduce this.

**Comment by EricWittmann** [comment]
@mfvitale do you have a link to that code?

**Comment by EricWittmann** [comment]
Also @mfvitale can you put together a reproducer?  I think this issue stalled out before for the same reason (no easy way for us to reproduce, because we don't work with DBZ often).

**Comment by mfvitale** [comment]
This is an example message 
[payload-example.txt](https://github.com/Apicurio/apicurio-registry/files/13702359/payload-example.txt)

**Comment by carlesarnal** [comment]
I have linked a PR that would solve this issue. Basically @mfvitale is right, the schema was null in convertToConnect resulting in parsing the json object as a map. I have solved it by building an envelope that contains both the schema and the payload so the schema is available for the transformation.
