### ISSUE TITLE
Unable to download artifacts with apicurio-registry-maven-plugin (RESTEASY003635)

### ISSUE THREAD

**Issue by stefanzilske** [Apicurio/apicurio-registry#2342]
Hey folks,

I try to use the Apicurio Maven plugin to download AVRO schema files. The registry is behind a Keycloak, so I specified that as auth server. But still, I am getting this exception:

```
[INFO] --- apicurio-registry-maven-plugin:2.1.5.Final:download (default) @ order-import-service ---
[INFO] Downloading artifact [MyNamespace] / [MyAvroSchema] (version null).
[ERROR] Exception while downloading artifact [MyNamespace] / [MyAvroSchema]
io.apicurio.rest.client.auth.exception.AuthException: {"error":"RESTEASY003635: No match for accept header"}
        at io.apicurio.rest.client.auth.exception.AuthErrorHandler.handleErrorResponse(AuthErrorHandler.java:23)
        at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:46)
        at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:190)
        at io.apicurio.rest.client.auth.OidcAuth.requestAccessToken(OidcAuth.java:71)
        at io.apicurio.rest.client.auth.OidcAuth.apply(OidcAuth.java:59)
        at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:163)
        at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getLatestArtifact(RegistryClientImpl.java:76)
        at io.apicurio.registry.maven.DownloadRegistryMojo.executeInternal(DownloadRegistryMojo.java:97)
        at io.apicurio.registry.maven.AbstractRegistryMojo.execute(AbstractRegistryMojo.java:95)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:271)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:196)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
        at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is how I configured the plugin in `pom.xml`:

```
<plugin>
    <groupId>io.apicurio</groupId>
    <artifactId>apicurio-registry-maven-plugin</artifactId>
    <version>2.1.5.Final</version>
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>download</goal>
            </goals>
            <configuration>
                <registryUrl>https://my-registry-url/apis/registry/v2</registryUrl>
                <authServerUrl>KEYCLOAK_URL</authServerUrl>
                <clientId>KEYCLOAK_USER</clientId>
                <clientSecret>KEYCLOAK_SECRET</clientSecret>
                <artifacts>
                    <artifact>
                        <groupId>MyNamespace</groupId>
                        <artifactId>MyAvroSchema</artifactId>
                        <file>${project.build.directory}/downloaded-sources/avro/MyAvroSchema.avsc</file>
                        <overwrite>true</overwrite>
                    </artifact>
                </artifacts>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Any idea why this is happening? Unfortunately, I cannot see which exact request is failing.

Cheers,
Stefan

Edit: I am running v 2.2.1.Final of Apicurio:

```
{
"name": "Apicurio Registry (SQL)",
"description": "High performance, runtime registry for schemas and API designs.",
"version": "2.2.1.Final",
"builtOn": "2022-03-02T17:38:33Z"
}
```

**Comment by EricWittmann** [comment]
Probably a good idea to upgrade the version of the plugin you are using.

https://search.maven.org/artifact/io.apicurio/apicurio-registry-maven-plugin/2.2.1.Final/maven-plugin

**Comment by EricWittmann** [comment]
Also could you try running the maven build with debug enabled:

`mvn clean install --debug`

But I have to say, `No match for accept header` suggests that the REST client didn't send an HTTP `Accept` header, which would be very strange.

**Comment by carlesarnal** [comment]
As Eric suggested, my very first recommendation would be to use the same version in the plugin and in the server. We have tests *and* at least one example for this. I'll use them to try to reproduce this issue.

**Comment by carlesarnal** [comment]
I've never reproduced this successfully, if someone finds this in the future and can provide a reproducer, I would be more than happy to help.
