### ISSUE TITLE
Jersey client cannot parse replies from  RESTEasy server

### ISSUE THREAD

**Issue by jpechane** [Apicurio/apicurio-registry#236]
If Avro converter is used in Kafka COnnect then Jersey REST client must/should be used. The problem is that when an atifact like `/artifacts/dbserver1-key` is created the server anwers with
```
{"createdOn":1579862056239,"modifiedOn":1579864479545,"id":"dbserver1-key","version":3,"type":"AVRO","globalId":3}
```
Date fields are serialized as epoch milliseconds.

When the client tries to parse them it gets
```
connect_1    | SEVERE: Unable to deserialize property 'createdOn' because of: Error parsing class java.util.Date from value: 1579862056239. Check your @JsonbDateFormat has all time units for class java.util.Date type, or consider using org.eclipse.yasson.YassonProperties#ZERO_TIME_PARSE_DEFAULTING.
connect_1    | 2020-01-24 11:14:39,550 INFO   ||  WorkerSourceTask{id=inventory-connector-0} Committing offsets   [org.apache.kafka.connect.runtime.WorkerSourceTask]
connect_1    | 2020-01-24 11:14:39,550 INFO   ||  WorkerSourceTask{id=inventory-connector-0} flushing 0 outstanding messages for offset commit   [org.apache.kafka.connect.runtime.WorkerSourceTask]
connect_1    | 2020-01-24 11:14:39,550 ERROR  ||  WorkerSourceTask{id=inventory-connector-0} Task threw an uncaught and unrecoverable exception   [org.apache.kafka.connect.runtime.WorkerTask]
connect_1    | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
connect_1    | 	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:287)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:316)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:240)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
connect_1    | 	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
connect_1    | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
connect_1    | 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
connect_1    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
connect_1    | 	at java.base/java.lang.Thread.run(Thread.java:834)
connect_1    | Caused by: javax.ws.rs.ProcessingException: Error deserializing object from entity stream.
connect_1    | 	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.readFrom(JsonBindingProvider.java:77)
connect_1    | 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
connect_1    | 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
connect_1    | 	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
connect_1    | 	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1071)
connect_1    | 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:850)
connect_1    | 	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:810)
connect_1    | 	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:339)
connect_1    | 	at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:102)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
connect_1    | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:365)
connect_1    | 	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:240)
connect_1    | 	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:99)
connect_1    | 	at org.glassfish.jersey.microprofile.restclient.MethodModel.lambda$asynchronousCall$5(MethodModel.java:266)
connect_1    | 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
connect_1    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
connect_1    | 	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
connect_1    | 	at org.glassfish.jersey.client.JerseyInvocation$1.completed(JerseyInvocation.java:789)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:203)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime.access$200(ClientRuntime.java:61)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime$2.lambda$response$0(ClientRuntime.java:154)
connect_1    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
connect_1    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
connect_1    | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime$2.response(ClientRuntime.java:154)
connect_1    | 	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:268)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime.lambda$null$3(ClientRuntime.java:163)
connect_1    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
connect_1    | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
connect_1    | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
connect_1    | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
connect_1    | 	at org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$4(ClientRuntime.java:139)
connect_1    | 	at org.glassfish.jersey.microprofile.restclient.ExecutorServiceWrapper.lambda$wrap$1(ExecutorServiceWrapper.java:124)
connect_1    | 	... 5 more
connect_1    | Caused by: javax.json.bind.JsonbException: Unable to deserialize property 'createdOn' because of: Error parsing class java.util.Date from value: 1579862056239. Check your @JsonbDateFormat has all time units for class java.util.Date type, or consider using org.eclipse.yasson.YassonProperties#ZERO_TIME_PARSE_DEFAULTING.
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:90)
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserialize(AbstractContainerDeserializer.java:60)
connect_1    | 	at org.eclipse.yasson.internal.Unmarshaller.deserializeItem(Unmarshaller.java:68)
connect_1    | 	at org.eclipse.yasson.internal.Unmarshaller.deserialize(Unmarshaller.java:54)
connect_1    | 	at org.eclipse.yasson.internal.JsonBinding.deserialize(JsonBinding.java:53)
connect_1    | 	at org.eclipse.yasson.internal.JsonBinding.fromJson(JsonBinding.java:93)
connect_1    | 	at org.glassfish.jersey.jsonb.internal.JsonBindingProvider.readFrom(JsonBindingProvider.java:75)
connect_1    | 	... 44 more
connect_1    | Caused by: javax.json.bind.JsonbException: Error parsing class java.util.Date from value: 1579862056239. Check your @JsonbDateFormat has all time units for class java.util.Date type, or consider using org.eclipse.yasson.YassonProperties#ZERO_TIME_PARSE_DEFAULTING.
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractDateTimeDeserializer.deserialize(AbstractDateTimeDeserializer.java:71)
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractValueTypeDeserializer.deserialize(AbstractValueTypeDeserializer.java:64)
connect_1    | 	at org.eclipse.yasson.internal.serializer.ObjectDeserializer.deserializeNext(ObjectDeserializer.java:174)
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractContainerDeserializer.deserializeInternal(AbstractContainerDeserializer.java:84)
connect_1    | 	... 50 more
connect_1    | Caused by: java.time.format.DateTimeParseException: Text '1579862056239' could not be parsed at index 0
connect_1    | 	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
connect_1    | 	at java.base/java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1948)
connect_1    | 	at java.base/java.time.ZonedDateTime.parse(ZonedDateTime.java:598)
connect_1    | 	at org.eclipse.yasson.internal.serializer.DateTypeDeserializer.parseWithOrWithoutZone(DateTypeDeserializer.java:83)
connect_1    | 	at org.eclipse.yasson.internal.serializer.DateTypeDeserializer.parseDefault(DateTypeDeserializer.java:54)
connect_1    | 	at org.eclipse.yasson.internal.serializer.DateTypeDeserializer.parseDefault(DateTypeDeserializer.java:34)
connect_1    | 	at org.eclipse.yasson.internal.serializer.AbstractDateTimeDeserializer.deserialize(AbstractDateTimeDeserializer.java:69)
connect_1    | 	... 53 more
```

The clients expects it to be a string formatted value.

**Comment by alesj** [comment]
@EricWittmann well, this is no a bug ... it's a misconfiguration between server and client json Date serializers ...

It looks like Jackson JSON DateSerializer uses longs ...

  * For efficiency, we will serialize Dates as longs, instead of
  * potentially more readable Strings.

... where as Yasson expects Date in string format ... ?

Since the user can control its client easier the (s)he can control server,
I would say it's on the user/client to match server's configuration.

**Comment by jpechane** [comment]
@alesj Well, but if I deploy the converter into Kafka Connect, how can I configure it so it matches the server?

**Comment by alesj** [comment]
@jpechane Hmm ... I would guess there must be a way to config this stuff ...
Otoh, @EricWittmann @jsenko wdyt if we changed this createdOn, etc to plain timestamp ourselves -- pure long ... that way it would be solved for all ...

**Comment by jpechane** [comment]
@alesj The only way I've found is adding annotation to the offending fields - in this case the mapping would be unambiguous

**Comment by alesj** [comment]
Like I wrote, I think we can easily change this to plain long timestamp, as I think for us it's not that important that that is a Date instance. It's just an informative field / value ...

**Comment by EricWittmann** [comment]
+1 to changing to `Timestamp` if that fixes this issue.  I don't much care whether it's a Date or a Timestamp.  Are there any storage layer consequences to doing that?

**Comment by alesj** [comment]
>> Are there any storage layer consequences to doing that?
Doesn't look like it ...

**Comment by EricWittmann** [comment]
Fixed by https://github.com/Apicurio/apicurio-registry/pull/240
