### ISSUE TITLE
Different content format between 2.2.1.Final and 2.2.2.Final versions

### ISSUE THREAD

**Issue by rmarting** [Apicurio/apicurio-registry#2407]
My application has an Avro schema with this structure:

```json
{
  "name": "Message",
  "namespace": "io.jromanmartin.kafka.schema.avro",
  "type": "record",
  "doc": "Schema for a Message.",
  "fields": [
    {
      "name": "timestamp",
      "type": "long",
      "doc": "Message timestamp."
    },
    {
      "name": "content",
      "type": "string",
      "doc": "Message content."
    }
  ]
}
```

To publish it into Apicurio Registry I use the `apicurio-registry-maven-plugin` plugin successfully. However I found that the plugin doesn't work exactly between version 2.2.1.Final and latest one 2.2.2.Final.

This is the definition of the Apicurio Registry Maven Plugin:

```xml
                    <plugin>
                        <groupId>io.apicurio</groupId>
                        <artifactId>apicurio-registry-maven-plugin</artifactId>
                        <version>${apicurio.version}</version>
                        <executions>
                            <execution>
                                <phase>generate-sources</phase>
                                <goals>
                                    <goal>register</goal>
                                </goals>
                                <configuration>
                                    <registryUrl>${apicurio.registry.url}</registryUrl>
                                    <artifacts>
                                        <!-- Schema definition for SimpleTopicIdStrategy strategy -->
                                        <artifact>
                                            <groupId>default</groupId>
                                            <artifactId>messages</artifactId>
                                            <version>2.0</version>
                                            <type>AVRO</type>
                                            <file>
                                                ${project.basedir}/src/main/avro/message.avsc
                                            </file>
                                            <ifExists>RETURN_OR_UPDATE</ifExists>
                                            <canonicalize>true</canonicalize>
                                        </artifact>

                                        <!-- Schema definition for TopicIdStrategy strategy -->
                                        <artifact>
                                            <groupId>default</groupId>
                                            <artifactId>messages-value</artifactId>
                                            <version>2.0</version>
                                            <type>AVRO</type>
                                            <file>
                                                ${project.basedir}/src/main/avro/message.avsc
                                            </file>
                                            <ifExists>RETURN_OR_UPDATE</ifExists>
                                            <canonicalize>true</canonicalize>
                                        </artifact>

                                        <!-- Schema definition for RecordIdStrategy strategy -->
                                        <artifact>
                                            <groupId>io.jromanmartin.kafka.schema.avro</groupId>
                                            <artifactId>Message</artifactId>
                                            <version>2.0</version>
                                            <type>AVRO</type>
                                            <file>
                                                ${project.basedir}/src/main/avro/message.avsc
                                            </file>
                                            <ifExists>RETURN_OR_UPDATE</ifExists>
                                            <canonicalize>true</canonicalize>
                                        </artifact>
                                    </artifacts>
                                </configuration>
                            </execution>
```

If I deploy the avro schema with the version 2.2.1.Final then the content in Apicurio Registry is the same and my producers/consumers work successfully. However as soon upgrade to the latest version, then the content in Apicurio Registry is different:

```json
{
  "content": "{\n  \"name\": \"Message\",\n  \"namespace\": \"io.jromanmartin.kafka.schema.avro\",\n  \"type\": \"record\",\n  \"doc\": \"Schema for a Message.\",\n  \"fields\": [\n    {\n      \"name\": \"timestamp\",\n      \"type\": \"long\",\n      \"doc\": \"Message timestamp.\"\n    },\n    {\n      \"name\": \"content\",\n      \"type\": \"string\",\n      \"doc\": \"Message content.\"\n    }\n  ]\n}\n",
  "references": []
}
```

Then my consumers start to fail with the following exception:

```text
Apr 05, 2022 3:03:36 PM io.smallrye.reactive.messaging.kafka.impl.KafkaSource reportFailure
WARN: SRMSG18228: A failure has been reported for Kafka topics '[messages]'
io.apicurio.registry.rest.client.exception.RestClientException: RESTEASY003210: Could not find resource for full path: http://service-registry-service:8080/apis/registry/v2/ids/globalIds/42/references
	at io.apicurio.registry.rest.client.impl.ErrorHandler.handleErrorResponse(ErrorHandler.java:64)
	at io.apicurio.rest.client.response.ResponseHandler.handle(ResponseHandler.java:37)
	at io.apicurio.rest.client.response.ResponseHandler.handle(ResponseHandler.java:18)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:400)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:387)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:365)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:332)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:294)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$8(HttpContext.java:550)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

*Steps to reproduce*

1. Deploy the schema using Apicurio Maven Registry Plugin 2.2.1.Final
2. Produce a record and consume it with an Quarkus application using the same SerDe version 2.2.1.Final
3. Delete the schema from Apicuiro Registry
4. Deploy the schema using Apicurio Maven Registry Plugin 2.2.2.Final
5. Produce a record and consume it with an Quarkus application using the same SerDe version 2.2.2.Final

Is it required to do some kind of changes to apply the latest version of 2.2.2.Final, upgrading from the previous minor version?

Cheers.

**Comment by rmarting** [comment]
My application is available in this GitHub repo: https://github.com/rmarting/kafka-clients-quarkus-sample

Currently the master branch has the current status with 2.2.1.Final version, working successfully in an OCP 4.10 environment. As soon this version is upgraded to 2.2.2.Final version, then the application fails with the exception described above.

**Comment by rmarting** [comment]
Great @carlesarnal !!! Thanks for so fast fix!

Do you have any ETA to release 2.2.3.Final with the fix? Thanks again!

**Comment by EricWittmann** [comment]
Releases are cheap - we'll evaluate this tomorrow morning to discuss if there are any other quick fixes we can get merged prior to doing a 2.2.3.Final release.
