### ISSUE TITLE
REST Client examples NOT working

### ISSUE THREAD

**Issue by arindamdas25** [Apicurio/apicurio-registry#2507]
I'm following this example
https://github.com/Apicurio/apicurio-registry-examples/tree/master/rest-client

and while trying to run it I'm getting. It is pointing 2.2.1.Final and I've tried with 2.2.3.Final.  Can anyone help me what's wrong with this? 

`Exception in thread "main" java.lang.NoClassDefFoundError: io/apicurio/rest/client/spi/ApicurioHttpClientFactory
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:79)
	at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:63)
	at io.apicurio.registry.examples.SimpleRegistryDemo.createProperClient(SimpleRegistryDemo.java:53)
	at io.apicurio.registry.examples.SimpleRegistryDemo.<clinit>(SimpleRegistryDemo.java:29)
Caused by: java.lang.ClassNotFoundException: io.apicurio.rest.client.spi.ApicurioHttpClientFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more`

**Comment by EricWittmann** [comment]
Closed by @arindamdas25 but I'm pinging @carlesarnal just in case there's something here. :)

**Comment by EricWittmann** [comment]
OK maybe this is relevant?

https://github.com/Apicurio/apicurio-registry-examples/pull/34/files/d78915904e3064e4928e118a9ef672f4e8d7dce6..98db0d61d4d6075b4419a84bf691f9862aa2febb

**Comment by carlesarnal** [comment]
The factory is not present in previous release an this why is not present. Updating the examples to the latest version of Registry fixes this.
