### ISSUE TITLE
Library serialization error

### ISSUE THREAD

**Issue by subkanthi** [Apicurio/apicurio-registry#2637]
`2022-07-19 00:07:44,247 ERROR  ||  Failed to start task sink-connector-4   [org.apache.kafka.connect.runtime.Worker]
java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at io.apicurio.registry.serde.AbstractSchemaResolver.configure(AbstractSchemaResolver.java:91)
        at io.apicurio.registry.serde.DefaultSchemaResolver.configure(DefaultSchemaResolver.java:56)
        at io.apicurio.registry.serde.SchemaResolverConfigurer.configure(SchemaResolverConfigurer.java:75)
        at io.apicurio.registry.utils.converter.SerdeBasedConverter.configure(SerdeBasedConverter.java:82)
        at io.apicurio.registry.utils.converter.AvroConverter.configure(AvroConverter.java:72)
        at org.apache.kafka.connect.runtime.isolation.Plugins.newConverter(Plugins.java:277)
        at org.apache.kafka.connect.runtime.Worker.startTask(Worker.java:520)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startTask(DistributedHerder.java:1421)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$getTaskStartingCallable$22(DistributedHerder.java:1434)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at java.base/java.lang.CompoundEnumeration.nextElement(ClassLoader.java:3048)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1206)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1306)
        at java.base/java.util.ServiceLoader$2.next(ServiceLoader.java:1297)
        at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1395)
        at io.apicurio.rest.client.spi.ApicurioHttpClientFactory.resolveProviderInstance(ApicurioHttpClientFactory.java:34)
        at io.apicurio.rest.client.spi.ApicurioHttpClientFactory.create(ApicurioHttpClientFactory.java:22)
        at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:79)
        at io.apicurio.registry.rest.client.RegistryClientFactory.create(RegistryClientFactory.java:67)
        at io.apicurio.registry.serde.AbstractSchemaResolver.configure(AbstractSchemaResolver.java:87)
        ... 12 more`

**Comment by carlesarnal** [comment]
Hello @subkanthi,

To be able to help you, we need some more information, especially the version of the client libraries you're using.

Thanks!

**Comment by subkanthi** [comment]
Hi @carlesarnal ,
we used Apicurio 2.1.5 Final
https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/2.1.5.Final/apicurio-registry-distro-connect-converter-2.1.5.Final.tar.gz'
And we tested with debezium 1.9.5 final

Thanks,

**Comment by carlesarnal** [comment]
This turned out to be an issue in the underlying library owned by us, so I fixed it there [here](https://github.com/Apicurio/apicurio-common-rest-client/pull/102). Once we update the version of the library here, this will be fixed.

**Comment by carlesarnal** [comment]
This will be fixed once https://github.com/Apicurio/apicurio-registry/pull/2786 is merged.
