### ISSUE TITLE
Protobuf schema version upload failing with NullPointerException

### ISSUE THREAD

**Issue by ozarkblue** [Apicurio/apicurio-registry#2877]
Added proto schema successfully in Registry through API with below details. 
Then while trying to update changing body (removing one field) its failing.

Similar result for UI upload artifact then upload a new version as well.

Note - same API working for JSON schema fine. Problem with Protobuf

https://host-name/apis/registry/v2/groups/G100/artifacts?ifExists=RETURN_OR_UPDATE
header:
X-Registry-ArtifactType = PROTOBUF
X-Registry-ArtifactId = 0005

body :
message Person {
    required string name = 1;
    required int32 id = 2;
    optional string email = 3;

    repeated string numbers = 4;
}

![image](https://user-images.githubusercontent.com/109760446/195422466-4263c581-f077-4ca5-9b6d-479c76f72a3a.png)

Then tried to make same API call just removing last line from body:

Response : 
{
    "error_code": 500,
    "detail": "NullPointerException: ",
    "name": "NullPointerException"
}

![image](https://user-images.githubusercontent.com/109760446/195422685-1beb2c11-74ad-4522-bda6-867aee7cb0b6.png)

**Comment by ozarkblue** [comment]
@EricWittmann Would you pls check and let me know if I'm missing anything or its a bug to be fixed.

**Comment by jsenko** [comment]
I'm looking into this now

**Comment by jsenko** [comment]
hi @ozarkblue I couldn't reproduce your issue on `main` or `2.0.x`. Could you provide more information so we can determine what's happening?
- Registry version
- Persistence type
- Logs
- Reproducer script or at least `curl` commands
- Anything about the environment you think may be important. Are you deploying Registry locally?

**Comment by EricWittmann** [comment]
Pinging @ozarkblue 

We'll wait longer on this issue.  We take forever to respond to things sometimes too.  :)

**Comment by ozarkblue** [comment]
Sorry for late response on this. Busy working on Schema Registry though :)
Registry version : apicurio/apicurio-registry-sql: 2.2.5.Final
Persistence type :PostgreSQL

Ran test again as below:
created an artifact of type PROTOBUF first time calling below API POST endpoint  and it was a success: See header, body and success response below

![image](https://user-images.githubusercontent.com/109760446/202012761-a836f58e-703f-4324-9657-eb353eef6947.png)

![image](https://user-images.githubusercontent.com/109760446/202012890-111d7d6c-08fe-4b53-a270-cae1aab55b17.png)

Showing in Apicurio UI as well:
![image](https://user-images.githubusercontent.com/109760446/202013233-57d2053a-366b-488a-b8c1-954f79d9e8dc.png)
![image](https://user-images.githubusercontent.com/109760446/202013440-f9778328-227e-4aca-b415-2e0ddf8d2af9.png)


Then tried to update the content (see below,I removed last field)  and create a new version from API:It failed with nullpointer exception

**Comment by ozarkblue** [comment]
![image](https://user-images.githubusercontent.com/109760446/202013858-a3a927dd-ec03-4165-ab5e-627738fcc905.png)

**Comment by ozarkblue** [comment]
Log:2022-11-15 20:04:19 INFO <_> [io.apicurio.registry.metrics.health.liveness.ResponseErrorLivenessCheck] (executor-thread-28482) After this event, the error counter is 2 (out of the maximum 5 allowed).
2022-11-15 20:04:19 ERROR <_> [io.apicurio.registry.services.http.RegistryExceptionMapperService] (executor-thread-28482) [500 ERROR DETECTED] : null: java.lang.NullPointerException
	at io.apicurio.registry.rules.compatibility.protobuf.ProtobufCompatibilityCheckerLibrary.findDifferences(ProtobufCompatibilityCheckerLibrary.java:68)
	at io.apicurio.registry.rules.compatibility.protobuf.ProtobufCompatibilityCheckerLibrary.validate(ProtobufCompatibilityCheckerLibrary.java:55)
	at io.apicurio.registry.rules.compatibility.ProtobufCompatibilityChecker.testBackward(ProtobufCompatibilityChecker.java:132)
	at io.apicurio.registry.rules.compatibility.ProtobufCompatibilityChecker.testCompatibility(ProtobufCompatibilityChecker.java:48)
	at io.apicurio.registry.rules.compatibility.CompatibilityRuleExecutor.execute(CompatibilityRuleExecutor.java:63)
	at io.apicurio.registry.rules.compatibility.CompatibilityRuleExecutor_Subclass.execute$$superforward1(Unknown Source)
	at io.apicurio.registry.rules.compatibility.CompatibilityRuleExecutor_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.common.apps.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:53)
	at io.apicurio.common.apps.logging.LoggingInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.rules.compatibility.CompatibilityRuleExecutor_Subclass.execute(Unknown Source)
	at io.apicurio.registry.rules.compatibility.CompatibilityRuleExecutor_ClientProxy.execute(Unknown Source)
	at io.apicurio.registry.rules.RulesServiceImpl.applyRule(RulesServiceImpl.java:131)
	at io.apicurio.registry.rules.RulesServiceImpl.applyGlobalAndArtifactRules(RulesServiceImpl.java:99)
	at io.apicurio.registry.rules.RulesServiceImpl.applyRules(RulesServiceImpl.java:73)
	at io.apicurio.registry.rules.RulesServiceImpl_ClientProxy.applyRules(Unknown Source)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.updateArtifactInternal(GroupsResourceImpl.java:883)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.updateArtifactInternal(GroupsResourceImpl.java:865)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.handleIfExistsReturnOrUpdate(GroupsResourceImpl.java:860)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.handleIfExists(GroupsResourceImpl.java:845)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.createArtifactWithRefs(GroupsResourceImpl.java:683)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl.createArtifact(GroupsResourceImpl.java:598)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl_Subclass.createArtifact$$superforward1(Unknown Source)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl_Subclass$$function$$2.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.apicurio.common.apps.logging.LoggingInterceptor.logMethodEntry(LoggingInterceptor.java:53)
	at io.apicurio.common.apps.logging.LoggingInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.apicurio.registry.auth.AuthorizedInterceptor.authorizeMethod(AuthorizedInterceptor.java:149)
	at io.apicurio.registry.auth.AuthorizedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
	at io.apicurio.common.apps.logging.audit.AuditedInterceptor.auditMethod(AuditedInterceptor.java:76)
	at io.apicurio.common.apps.logging.audit.AuditedInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl_Subclass.createArtifact(Unknown Source)
	at io.apicurio.registry.rest.v2.GroupsResourceImpl_ClientProxy.createArtifact(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:35)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.registry.ui.servlets.HSTSFilter.doFilter(HSTSFilter.java:62)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.registry.ui.servlets.ResourceCacheControlFilter.doFilter(ResourceCacheControlFilter.java:92)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.apicurio.registry.rest.RegistryApplicationServletFilter.doFilter(RegistryApplicationServletFilter.java:163)
	at io.apicurio.registry.rest.RegistryApplicationServletFilter_ClientProxy.doFilter(Unknown Source)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$9$1.call(UndertowDeploymentRecorder.java:590)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:119)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:284)
	at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
	at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$5$1.run(UndertowDeploymentRecorder.java:412)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:545)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by ozarkblue** [comment]
Note: I did not enable any of the compatibility or syntax check rules.

**Comment by jsenko** [comment]
hi @ozarkblue I was able to reproduce this, thanks. You had a global compatibility rule enabled though. I'm looking into the error.
