### ISSUE TITLE
Avro deserialization error when using io.confluent.kafka.serializers.KafkaAvroDeserializer

### ISSUE THREAD

**Issue by hgeraldino** [Apicurio/apicurio-registry#2878]
## Description

**Registry
Version**: 2.2.5.Final
**Persistence type**: kafkasql

### Environment

1. docker-compose cluster
2. Apicurio 2.2.5.Final docker image with kafkasql persistence
3. fast-data-dev (https://github.com/lensesio/fast-data-dev) connect cluster
4. Debezium mysql example database: debezium/example-mysql:1.7

### Steps to Reproduce

I created a new Debezium MySqlConnector using Apicurio's `AvroConverter` for both Key and Value.

Connector configuration excerpt:
```
name=inventory-mysql-connector
connector.class=io.debezium.connector.mysql.MySqlConnector
database.user=debezium
tasks.max=1
... // debezium connector configs
key.converter=io.apicurio.registry.utils.converter.AvroConverter
key.converter.apicurio.registry.url=http://apicurio:8080/
key.converter.apicurio.registry.auto-register=true
key.converter.apicurio.registry.use-id=contentId
key.converter.apicurio.registry.as-confluent=true
key.converter.apicurio.registry.global-id=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
key.converter.apicurio.registry.artifact-resolver-strategy=io.apicurio.registry.serde.avro.strategy.TopicRecordIdStrategy
value.converter=io.apicurio.registry.utils.converter.AvroConverter
value.converter.apicurio.registry.url=http://apicurio:8080/
value.converter.apicurio.registry.global-id=io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
value.converter.apicurio.registry.artifact-resolver-strategy=io.apicurio.registry.serde.avro.strategy.TopicRecordIdStrategy
value.converter.apicurio.registry.auto-register=true
value.converter.apicurio.registry.use-id=contentId
value.converter.apicurio.registry.as-confluent=true
```

Everything works fine: I can see the messages being encoded with Avro, and the schemas are registered on the Apicurio registry. I can read messages using Apicurio's `io.apicurio.registry.serde.avro.AvroKafkaDeserializer`.

Now, we have other clients that are using Confluent's `io.confluent.kafka.serializers.KafkaAvroDeserializer` deserializers (there are also confluent-kafka-python and librdkafka/libserdes clients that would need to consume these messages, but we'll leave these out for now)

When configuring a Kafka consumer to use the `KafkaAvroDeserializer`, I set the `schema.registry.url` to the compatibility URL (http://apicurio:8080/apis/ccompat/v6). The client is able to fetch the schema, but fails when trying to decode the message because the published schema is including what seems to be a synthetic `io.debezium.connector.mysql.Source` reference schema (with version 1), that is not being published to Apicurio.

This is what I see when querying the v2 and ccompat/v6 endpoints:

```
$ curl -q  http://localhost:8080/apis/registry/v2/ids/contentIds/9 | json_pp
{
   "connect.name" : "dbserver1.inventory.customers.Envelope",
   "fields" : [
      {
         "default" : null,
         "name" : "before",
         "type" : [
            "null",
            {
               "connect.name" : "dbserver1.inventory.customers.Value",
               "fields" : [
                  {
                     "name" : "id",
                     "type" : "int"
                  },
                  {
                     "name" : "first_name",
                     "type" : "string"
                  },
                  {
                     "name" : "last_name",
                     "type" : "string"
                  },
                  {
                     "name" : "email",
                     "type" : "string"
                  }
               ],
               "name" : "Value",
               "type" : "record"
            }
         ]
      },
      {
         "default" : null,
         "name" : "after",
         "type" : [
            "null",
            "Value"
         ]
      },
      {
         "name" : "source",
         "type" : "io.debezium.connector.mysql.Source"
      },
      {
         "name" : "op",
         "type" : "string"
      },
      {
         "default" : null,
         "name" : "ts_ms",
         "type" : [
            "null",
            "long"
         ]
      }
   ],
   "name" : "Envelope",
   "namespace" : "dbserver1.inventory.customers",
   "type" : "record"
}
```

```
$ curl -q  http://localhost:8080/apis/ccompat/v6/schemas/ids/9 | jq '.' 
{
  "schema": "{\"type\":\"record\",\"name\":\"Envelope\",\"namespace\":\"dbserver1.inventory.customers\",\"fields\":[{\"name\":\"before\",\"type\":[\"null\",{\"type\":\"record\",\"name\":\"Value\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"first_name\",\"type\":\"string\"},{\"name\":\"last_name\",\"type\":\"string\"},{\"name\":\"email\",\"type\":\"string\"}],\"connect.name\":\"dbserver1.inventory.customers.Value\"}],\"default\":null},{\"name\":\"after\",\"type\":[\"null\",\"Value\"],\"default\":null},{\"name\":\"source\",\"type\":\"io.debezium.connector.mysql.Source\"},{\"name\":\"op\",\"type\":\"string\"},{\"name\":\"ts_ms\",\"type\":[\"null\",\"long\"],\"default\":null}],\"connect.name\":\"dbserver1.inventory.customers.Envelope\"}",
  "references": [
    {
      "name": "io.debezium.connector.mysql.Source",
      "subject": "io.debezium.connector.mysql.Source",
      "version": 1
    }
  ]
}
```

As you can see, the ccompat/v6 version incudes a `references` field with the schema definition for the `source` field, whereas the v2 endpoint did not. This is breaking the `KafkaAvroDeserializer` with the following stacktrace:

```
Exception in thread "main" org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition dbserver1.inventory.customers-0 at offset 0. If needed, please seek past the record to continue consumption.
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro unknown schema for id 8
Caused by: java.io.IOException: Invalid schema {"type":"record","name":"Envelope","namespace":"dbserver1.inventory.customers","fields":[{"name":"before","type":["null",{"type":"record","name":"Value","fields":[{"name":"id","type":"int"},{"name":"first_name","type":"string"},{"name":"last_name","type":"string"},{"name":"email","type":"string"}],"connect.name":"dbserver1.inventory.customers.Value"}],"default":null},{"name":"after","type":["null","Value"],"default":null},{"name":"source","type":"io.debezium.connector.mysql.Source"},{"name":"op","type":"string"},{"name":"ts_ms","type":["null","long"],"default":null}],"connect.name":"dbserver1.inventory.customers.Envelope"} with refs [{name='io.debezium.connector.mysql.Source', subject='io.debezium.connector.mysql.Source', version=1}] of type AVRO
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.lambda$getSchemaByIdFromRegistry$4(CachedSchemaRegistryClient.java:222)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:220)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaBySubjectAndId(CachedSchemaRegistryClient.java:291)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaById(CachedSchemaRegistryClient.java:276)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer$DeserializationContext.schemaFromRegistry(AbstractKafkaAvroDeserializer.java:273)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:97)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:76)
	at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:55)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
	at org.apache.kafka.clients.consumer.internals.Fetcher.parseRecord(Fetcher.java:1386)
	at org.apache.kafka.clients.consumer.internals.Fetcher.access$3400(Fetcher.java:133)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.fetchRecords(Fetcher.java:1617)
	at org.apache.kafka.clients.consumer.internals.Fetcher$CompletedFetch.access$1700(Fetcher.java:1453)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:686)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:637)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1303)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1237)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1210)
	at io.apicurio.registry.examples.confluent.serdes.ConfluentSerdesExample.main(ConfluentSerdesExample.java:128)
```

A similar error happens when I try to decode these using kafkacat:

```
$ kcat -C -b localhost:9092  -t dbserver1.inventory.customers -s key=avro -s value=avro -r http://localhost:8080/apis/ccompat/v6  -o beginning
% ERROR: Failed to format message in dbserver1.inventory.customers [0] at offset 0: Avro/Schema-registry message deserialization: Unknown Avro "type": io.debezium.connector.mysql.Source: terminating
{"id": 1001}%                     
```

### Expected vs Actual Behaviour

I would expect the contents of v2 and ccompat/v6 schemas to be the same. It's not clear (to me) why a separate `references` field is being created by the AvroConverter and persisted on the KafkaSqlSink

**Comment by carlesarnal** [comment]
@hgeraldino you have an example [here](https://github.com/Apicurio/apicurio-registry-examples/tree/main/event-driven-architecture) on how to setup Debezium, Kafka connect etc. Long story short is that you're expecting two completely different APIs to work the same way, and that is not the case. [Here](https://github.com/confluentinc/schema-registry/blob/cde81674c7929c769ceddb848e8b5e75132da1fa/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/entities/SchemaString.java#L34)'s the object being used in confluent and, as you can see, there is a references field on it.

Two important notes here are that kafkacat does not support references AFAIK and the confluent KafkaAvroDeserializer version is also very important since references were not supported a few versions ago.
