### ISSUE TITLE
Kafka JDBC Sink Connector with Apicurio registry

### ISSUE THREAD

**Issue by mschuch** [Apicurio/apicurio-registry#2896]
Hi,

I want to use Kafka connect and the apicurio registry.
A Kafka Producer and Consumer are both working with the examples from apicurio repository (simple-avro, simple-avor-maven).
So I can say that the configuration of the urls are working, but if i use a kafka connector with the apicurio serde config and are using the same as in the producer I get an exception:

```
{
    "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.apicurio.registry.utils.converter.AvroConverter",
    "topics": "output_table_topic",
    "connection.url": "jdbc:postgresql://localhost:5432/",
    "connection.user": "postgres",
    "connection.password": "mysecretpassword",
    "table.name.format": "output_table",
    "auto.create": "false",
    "value.converter.apicurio.registry.url": "http://localhost:8093/apis/registry/v2"
    "value.converter.apicurio.registry.auto-register": "true",
    "value.converter.apicurio.registry.find-latest": "true",
    "value.converter.apicurio.registry.artifact.artifact-id": "output_table_topic-value",
    "pk.mode": "record_value",
    "pk.fields": "id"
}
```
```
[2022-10-19 13:57:36,671] ERROR WorkerSinkTask{id=Test-0} Error converting message value in topic 'output_table_topic' partition 0 at offset 25 and timestamp 1666187856301: Connection refused (org.apache.kafka.connect.runtime.WorkerSinkTask)
io.apicurio.registry.rest.client.exception.RestClientException: Connection refused
        at io.apicurio.registry.rest.client.impl.ErrorHandler.parseError(ErrorHandler.java:95)
        at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:207)
        at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getContentByGlobalId(RegistryClientImpl.java:324)
        at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:183)
        at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:142)
        at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:181)
        at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:141)
        at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:116)
        at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:178)
        at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:164)
        at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
        at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:136)
        at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:122)
        at io.apicurio.registry.utils.converter.SerdeBasedConverter.toConnectData(SerdeBasedConverter.java:139)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertValue(WorkerSinkTask.java:545)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$1(WorkerSinkTask.java:501)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:156)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:190)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:132)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:501)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:478)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:328)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:238)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

Does anybody see what i am doing wrong?

**Comment by hgeraldino** [comment]
That `Connection refused` error implies that the Kafka connect worker task is unable to reach the Apicurio REST endpoint. Wondering if your Kafka Connect instance is running in the same host as Apicurio (I'd also check for any proxies being set)

**Comment by mschuch** [comment]
Yeah, you were totally right, I forgot that kafka connect could not resolve localhost, because of the internal docker network.
Now everything seems to be fine. Thank you.
