### ISSUE TITLE
No artifact with ID '3227' in group 'null' was found.

### ISSUE THREAD

**Issue by pradeepbhat4591** [Apicurio/apicurio-registry#2912]
```
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.apicurio.registry.rest.client.exception.ArtifactNotFoundException: No artifact with ID '3227' in group 'null' was found.
	at io.apicurio.registry.rest.client.exception.ExceptionMapper.map(ExceptionMapper.java:33)
	at io.apicurio.registry.rest.client.impl.ErrorHandler.handleErrorResponse(ErrorHandler.java:64)
	at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:46)
	at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:202)
	at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getContentByGlobalId(RegistryClientImpl.java:251)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:166)
	at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:132)
	at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:171)
	at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:131)
	at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:111)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:162)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:122)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:104)
	at io.apicurio.registry.utils.converter.SerdeBasedConverter.toConnectData(SerdeBasedConverter.java:129)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:88)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
	... 13 more
```

**Comment by pradeepbhat4591** [comment]
I'm using apicurio-registry-distro-connect-converter-2.2.1.Final jar

**Comment by carlesarnal** [comment]
Hi @pradeepbhat4591,

With that little detail is a bit hard for us to help you. Please share more context like your configuration, and the schemas you're using and, if you can share a reproducer, that would be awesome.

Thanks

**Comment by EricWittmann** [comment]
The stack trace suggests that the configuration of the connector is off, because unless you actually set the ID of your artifact to `3227`, the connector is probably trying to use the `globalId` or `contentId` of the artifact to lookup the content using the API endpoint that is meant for group+artifact information.

In other words, there are multiple ways to lookup an artifact in the registry.  Including:

* Using artifact id + group + (optional) version
* Using just the `globalId` (unique ID for a specific version of an artifact)
* Using just the `contentId` (unique ID for the **content** of an artifact version, shared if you were to upload the same byte content multiple times)

Each of these have their own endpoint/operation in the REST API.  The stack trace suggests to me that the endpoint for (1) above is being used but information from either (2) or (3) is being passed.

+1 to Carles' response though - we need your connector config at a minimum.
