### ISSUE TITLE
Cannot deserialize value of type `java.util.Date` from String "2023-02-08T15:58:32Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"

### ISSUE THREAD

**Issue by coetzeevs** [Apicurio/apicurio-registry#3140]
## Description

*Note: apologies up front if this turns out not to be related to Apicurio specifically. From my base understanding though, it appears to be related. 

**Registry
Version**: `2.4.1.Final`
**Persistence type**: `sql` and `mem`

### Environment

Running in docker, see below. Specifically attempting to run a simple MySQL Source Connector using Debezium-maintained images using version `latest`. See below. 

<details>
  <summary>docker-compose.yaml</summary>

```YAML
  version: '3.1'
  
  services:
    zookeeper:
      image: quay.io/debezium/zookeeper:latest
      ports:
       - 2181:2181
       - 2888:2888
       - 3888:3888
    kafka:
      image: quay.io/debezium/kafka:latest
      ports:
       - 9092:9092
      links:
       - zookeeper
      environment:
       - ZOOKEEPER_CONNECT=zookeeper:2181
    mysql:
      image: quay.io/debezium/example-mysql:latest
      ports:
       - 3306:3306
      environment:
       - MYSQL_ROOT_PASSWORD=debezium
       - MYSQL_USER=mysqluser
       - MYSQL_PASSWORD=mysqlpw
    postgres:
      image: postgres
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: apicurio-registry
        POSTGRES_PASSWORD: password
    apicurio:
      image: apicurio/apicurio-registry-sql:2.4.1.Final
      ports:
        - 8080:8080
      environment:
        REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
        REGISTRY_DATASOURCE_USERNAME: apicurio-registry
        REGISTRY_DATASOURCE_PASSWORD: password
    connect:
      image: quay.io/debezium/connect:latest
      ports:
       - 8083:8083
      links:
       - kafka
       - mysql
       - apicurio
      environment:
        - BOOTSTRAP_SERVERS=kafka:9092
        - GROUP_ID=1
        - CONFIG_STORAGE_TOPIC=my_connect_configs
        - OFFSET_STORAGE_TOPIC=my_connect_offsets
        - STATUS_STORAGE_TOPIC=my_connect_statuses
        - ENABLE_APICURIO_CONVERTERS=true
        - KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
        - VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
        - CONNECT_KEY_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
        - CONNECT_KEY_CONVERTER_APICURIO.REGISTRY_URL=http://apicurio:8080/apis/registry/v2
        - CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER=true
        - CONNECT_KEY_CONVERTER_APICURIO_REGISTRY_FIND-LATEST=true
        - CONNECT_VALUE_CONVERTER=io.apicurio.registry.utils.converter.AvroConverter
        - CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_URL=http://apicurio:8080/apis/registry/v2
        - CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_AUTO-REGISTER=true
        - CONNECT_VALUE_CONVERTER_APICURIO_REGISTRY_FIND-LATEST=true
        - CONNECT_SCHEMA_NAME_ADJUSTMENT_MODE=avro
```
</details>

<details>
  <summary>connector.json</summary>

```JSON
{
    "name": "inventory-connector",
    "config": {
        "connector.class": "io.debezium.connector.mysql.MySqlConnector",
        "tasks.max": "1",
        "database.hostname": "mysql",
        "database.port": "3306",
        "database.user": "dbz_user",
        "database.password": "debeziumPWD",
        "database.server.id": "184054",
        "database.server.name": "localhost",
        "database.allowPublicKeyRetrieval":"true",
        "include.schema.changes": "true",
        "topic.prefix": "dbserver1",
        "database.history.kafka.topic": "db_history_topic",
        "database.history.kafka.bootstrap.servers": "kafka:9092",
        "database.include.list": "inventory",
        "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
        "schema.history.internal.kafka.topic": "schema-changes.inventory",
        "key.converter": "io.apicurio.registry.utils.converter.AvroConverter",
        "key.converter.apicurio.registry.url": "http://apicurio:8080/apis/registry/v2",
        "key.converter.apicurio.registry.auto-register": "true",
        "key.converter.apicurio.registry.find-latest": "true",
        "value.converter": "io.apicurio.registry.utils.converter.AvroConverter",
        "value.converter.apicurio.registry.url": "http://apicurio:8080/apis/registry/v2",
        "value.converter.apicurio.registry.auto-register": "true",
        "value.converter.apicurio.registry.find-latest": "true",
        "schema.name.adjustment.mode": "avro"
    }
}
```
</details>

### Steps to Reproduce

1. Run `docker-compose -f docker-compose.yaml up`
2. Create the connector using
```bash
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" \
    http://localhost:8083/connectors/ -d @register-mysql-apicurio-converter-avro.json
```
3. Observe the output in Kafka Connect logs.

### Expected vs Actual Behaviour

Expected: Successfully establish a MySQL Source Connector with running tasks to read binlogs from the DB and write to a set of topics, creating relevant schema artifacts in Apicurio Registry that is viewable/retrievable. 

Actual: Connector task shutdown due to error tolerance being exceeded, caused by `Cannot deserialize value of type ´java.util.Date´ from String "2023-02-08T15:58:32Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"`

Full trace of error logs attached as well.

### Logs

<details>
  <summary>Logs</summary>
  
```bash
2023-02-08 16:01:55 2023-02-08 16:01:55,098 INFO   MySQL|localhost|snapshot  Metrics registered   [io.debezium.pipeline.ChangeEventSourceCoordinator]
2023-02-08 16:01:55 2023-02-08 16:01:55,098 INFO   MySQL|localhost|snapshot  Context created   [io.debezium.pipeline.ChangeEventSourceCoordinator]
2023-02-08 16:01:55 2023-02-08 16:01:55,099 INFO   MySQL|localhost|snapshot  No previous offset has been found   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,099 INFO   MySQL|localhost|snapshot  According to the connector configuration both schema and data will be snapshotted   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,099 INFO   MySQL|localhost|snapshot  Snapshot step 1 - Preparing   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,107 INFO   MySQL|localhost|snapshot  Snapshot step 2 - Determining captured tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,109 INFO   MySQL|localhost|snapshot  Read list of available databases   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,121 INFO   MySQL|localhost|snapshot      list of available databases is: [information_schema, inventory, mysql, performance_schema, sys]   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,121 INFO   MySQL|localhost|snapshot  Read list of available tables in each database   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,169 INFO   MySQL|localhost|snapshot     snapshot continuing with database(s): [inventory]   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,170 INFO   MySQL|localhost|snapshot  Adding table inventory.addresses to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,170 INFO   MySQL|localhost|snapshot  Adding table inventory.customers to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,170 INFO   MySQL|localhost|snapshot  Adding table inventory.orders to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,171 INFO   MySQL|localhost|snapshot  Adding table inventory.geom to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,171 INFO   MySQL|localhost|snapshot  Adding table inventory.products_on_hand to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,171 INFO   MySQL|localhost|snapshot  Adding table inventory.products to the list of capture schema tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,174 INFO   MySQL|localhost|snapshot  Snapshot step 3 - Locking captured tables [inventory.addresses, inventory.customers, inventory.geom, inventory.orders, inventory.products, inventory.products_on_hand]   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,177 INFO   MySQL|localhost|snapshot  Flush and obtain global read lock to prevent writes to database   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,184 INFO   MySQL|localhost|snapshot  Snapshot step 4 - Determining snapshot offset   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,184 INFO   MySQL|localhost|snapshot  Read binlog position of MySQL primary server   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,186 INFO   MySQL|localhost|snapshot      using binlog 'mysql-bin.000006' at position '157' and gtid ''   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,186 INFO   MySQL|localhost|snapshot  Snapshot step 5 - Reading structure of captured tables   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,186 INFO   MySQL|localhost|snapshot  All eligible tables schema should be captured, capturing: [inventory.addresses, inventory.customers, inventory.geom, inventory.orders, inventory.products, inventory.products_on_hand]   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,307 INFO   MySQL|localhost|snapshot  Reading structure of database 'inventory'   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,424 INFO   MySQL|localhost|snapshot  Snapshot step 6 - Persisting schema history   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,446 INFO   ||  [Producer clientId=localhost-dbhistory] Resetting the last seen epoch of partition db_history_topic-0 to 0 since the associated topicId changed from null to xxiB0RBJTSGmmJDTWV5Icw   [org.apache.kafka.clients.Metadata]
2023-02-08 16:01:55 2023-02-08 16:01:55,579 INFO   MySQL|localhost|snapshot  Releasing global read lock to enable MySQL writes   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,581 INFO   MySQL|localhost|snapshot  Writes to MySQL tables prevented for a total of 00:00:00.398   [io.debezium.connector.mysql.MySqlSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,582 INFO   MySQL|localhost|snapshot  Snapshot step 7 - Snapshotting data   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,582 INFO   MySQL|localhost|snapshot  Snapshotting contents of 6 tables while still in transaction   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,582 INFO   MySQL|localhost|snapshot  Exporting data from table 'inventory.addresses' (1 of 6 tables)   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,583 INFO   MySQL|localhost|snapshot      For table 'inventory.addresses' using select statement: 'SELECT `id`, `customer_id`, `street`, `city`, `state`, `zip`, `type` FROM `inventory`.`addresses`'   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,626 INFO   MySQL|localhost|snapshot      Finished exporting 7 records for table 'inventory.addresses'; total duration '00:00:00.043'   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,627 INFO   MySQL|localhost|snapshot  Exporting data from table 'inventory.customers' (2 of 6 tables)   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,628 INFO   MySQL|localhost|snapshot      For table 'inventory.customers' using select statement: 'SELECT `id`, `first_name`, `last_name`, `email` FROM `inventory`.`customers`'   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,650 INFO   MySQL|localhost|snapshot      Finished exporting 4 records for table 'inventory.customers'; total duration '00:00:00.022'   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,651 INFO   MySQL|localhost|snapshot  Exporting data from table 'inventory.geom' (3 of 6 tables)   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,652 INFO   MySQL|localhost|snapshot      For table 'inventory.geom' using select statement: 'SELECT `id`, `g`, `h` FROM `inventory`.`geom`'   [io.debezium.relational.RelationalSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,668 ERROR  ||  WorkerSourceTask{id=inventory-connector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
2023-02-08 16:01:55 org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:223)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerSourceTask.convertTransformedRecord(WorkerSourceTask.java:327)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:356)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:258)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
2023-02-08 16:01:55     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-02-08 16:01:55     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-08 16:01:55     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-08 16:01:55     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-08 16:01:55     at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-08 16:01:55 Caused by: java.io.UncheckedIOException: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2023-02-08T15:58:32Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"
2023-02-08 16:01:55  at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 54] (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])
2023-02-08 16:01:55     at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:60)
2023-02-08 16:01:55     at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:190)
2023-02-08 16:01:55     at io.apicurio.registry.rest.client.impl.RegistryClientImpl.createArtifact(RegistryClientImpl.java:236)
2023-02-08 16:01:55     at io.apicurio.registry.rest.client.RegistryClient.createArtifact(RegistryClient.java:139)
2023-02-08 16:01:55     at io.apicurio.registry.serde.DefaultSchemaResolver.lambda$handleAutoCreateArtifact$2(DefaultSchemaResolver.java:174)
2023-02-08 16:01:55     at io.apicurio.registry.serde.ERCache.lambda$getValue$0(ERCache.java:132)
2023-02-08 16:01:55     at io.apicurio.registry.serde.ERCache.retry(ERCache.java:171)
2023-02-08 16:01:55     at io.apicurio.registry.serde.ERCache.getValue(ERCache.java:131)
2023-02-08 16:01:55     at io.apicurio.registry.serde.ERCache.getByContent(ERCache.java:116)
2023-02-08 16:01:55     at io.apicurio.registry.serde.DefaultSchemaResolver.handleAutoCreateArtifact(DefaultSchemaResolver.java:172)
2023-02-08 16:01:55     at io.apicurio.registry.serde.DefaultSchemaResolver.resolveSchema(DefaultSchemaResolver.java:82)
2023-02-08 16:01:55     at io.apicurio.registry.serde.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:92)
2023-02-08 16:01:55     at io.apicurio.registry.serde.AbstractKafkaSerializer.serialize(AbstractKafkaSerializer.java:79)
2023-02-08 16:01:55     at io.apicurio.registry.utils.converter.SerdeBasedConverter.fromConnectData(SerdeBasedConverter.java:111)
2023-02-08 16:01:55     at org.apache.kafka.connect.storage.Converter.fromConnectData(Converter.java:64)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.WorkerSourceTask.lambda$convertTransformedRecord$2(WorkerSourceTask.java:327)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
2023-02-08 16:01:55     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
2023-02-08 16:01:55     ... 11 more
2023-02-08 16:01:55 Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.util.Date` from String "2023-02-08T15:58:32Z": expected format "yyyy-MM-dd'T'HH:mm:ssZ"
2023-02-08 16:01:55  at [Source: (jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream); line: 1, column: 54] (through reference chain: io.apicurio.registry.rest.v2.beans.ArtifactMetaData["createdOn"])
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1851)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:1079)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateBasedDeserializer._parseDate(DateDeserializers.java:195)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:303)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.std.DateDeserializers$DateDeserializer.deserialize(DateDeserializers.java:281)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:324)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4593)
2023-02-08 16:01:55     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3593)
2023-02-08 16:01:55     at io.apicurio.rest.client.handler.BodyHandler.lambda$toSupplierOfType$1(BodyHandler.java:56)
2023-02-08 16:01:55     ... 28 more
2023-02-08 16:01:55 2023-02-08 16:01:55,670 INFO   ||  Stopping down connector   [io.debezium.connector.common.BaseSourceTask]
2023-02-08 16:01:55 2023-02-08 16:01:55,678 WARN   MySQL|localhost|snapshot  Snapshot was interrupted before completion   [io.debezium.pipeline.source.AbstractSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,679 INFO   MySQL|localhost|snapshot  Snapshot - Final stage   [io.debezium.pipeline.source.AbstractSnapshotChangeEventSource]
2023-02-08 16:01:55 2023-02-08 16:01:55,679 WARN   MySQL|localhost|snapshot  Change event source executor was interrupted   [io.debezium.pipeline.ChangeEventSourceCoordinator]
2023-02-08 16:01:55 java.lang.InterruptedException: Interrupted while snapshotting table inventory.geom
2023-02-08 16:01:55     at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEventsForTable(RelationalSnapshotChangeEventSource.java:383)
2023-02-08 16:01:55     at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:316)
2023-02-08 16:01:55     at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:132)
2023-02-08 16:01:55     at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:76)
2023-02-08 16:01:55     at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:155)
2023-02-08 16:01:55     at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:137)
2023-02-08 16:01:55     at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:109)
2023-02-08 16:01:55     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2023-02-08 16:01:55     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2023-02-08 16:01:55     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2023-02-08 16:01:55     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2023-02-08 16:01:55     at java.base/java.lang.Thread.run(Thread.java:829)
2023-02-08 16:01:55 2023-02-08 16:01:55,685 INFO   ||  Connection gracefully closed   [io.debezium.jdbc.JdbcConnection]
2023-02-08 16:01:55 2023-02-08 16:01:55,686 INFO   ||  [Producer clientId=localhost-dbhistory] Closing the Kafka producer with timeoutMillis = 30000 ms.   [org.apache.kafka.clients.producer.KafkaProducer]
2023-02-08 16:01:55 2023-02-08 16:01:55,693 INFO   ||  Metrics scheduler closed   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,693 INFO   ||  Closing reporter org.apache.kafka.common.metrics.JmxReporter   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,694 INFO   ||  Metrics reporters closed   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,694 INFO   ||  App info kafka.producer for localhost-dbhistory unregistered   [org.apache.kafka.common.utils.AppInfoParser]
2023-02-08 16:01:55 2023-02-08 16:01:55,694 INFO   ||  [Producer clientId=connector-producer-inventory-connector-0] Closing the Kafka producer with timeoutMillis = 30000 ms.   [org.apache.kafka.clients.producer.KafkaProducer]
2023-02-08 16:01:55 2023-02-08 16:01:55,701 INFO   ||  Metrics scheduler closed   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,701 INFO   ||  Closing reporter org.apache.kafka.common.metrics.JmxReporter   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,701 INFO   ||  Metrics reporters closed   [org.apache.kafka.common.metrics.Metrics]
2023-02-08 16:01:55 2023-02-08 16:01:55,702 INFO   ||  App info kafka.producer for connector-producer-inventory-connector-0 unregistered   [org.apache.kafka.common.utils.AppInfoParser]
```
</details>

**Comment by carlesarnal** [comment]
Hi @coetzeevs,

I think you're mixing client and server versions, you have a lot more context [here](https://github.com/Apicurio/apicurio-registry/issues/3024) I'm closing this since this problem is fixed but, if you have any other problems please, re-open.

**Comment by coetzeevs** [comment]
For anyone coming across this, it's 100% a mismatch in versions between client and server. I was using the `latest` image tag for Debezium images which hadn't been upgraded to use `2.4.x` from Apicurio. Once I switched to the `2.2` images for Debezium (which is currently an alpha release) the problem was resolved.

**Comment by nvlong198** [comment]
@coetzeevs @carlesarnal Currently I using Debezium 1.9.7, and I just want to upgrade Apicurio to a newer version,
Could I do that? I do not find any Apicurio x Debezium compatibility in the recent version.

**Comment by carlesarnal** [comment]
So, for Apicurio Registry there are two things, the client libraries, in this case, packed with Debezium and the Apicurio Registry server, and I guess that's the version you're talking about (if you want to upgrade the client, it's as simple as updating Debezium).

If you only update the server *without* updating the client, it will fail. If you update the client (to, at least, 2.4.1), it will work since in  2.4.1 we made the client retro compatible so it doesn't fail in situations like this.

So, long story to say that you must update first your client libraries and then the server.
