### ISSUE TITLE
io.apicurio.registry.rest.client.exception.RestClientException: HTTP/1.1 header parser received no bytes

### ISSUE THREAD

**Issue by HelloSunilSaini** [Apicurio/apicurio-registry#3276]
## Description

**Registry
Version**: 2.3.1
**Persistence type**: sql

### Environment

kubernetes server version : version.Info{Major:"1", Minor:"23+", GitVersion:"v1.23.16-eks-48e63af", GitCommit:"e6332a8a3feb9e0fe3db851878f88cb73d49dd7a", GitTreeState:"clean", BuildDate:"2023-01-24T19:18:15Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}

sardes client : apicurio-registry-distro-connect-converter-2.3.1.Final

### Expected vs Actual Behaviour

i was expecting kafka connect to retry this but as its not an instance of [RetriableException](https://kafka.apache.org/21/javadoc/org/apache/kafka/common/errors/RetriableException.html) kafka connect will not retry it want it to be retriableException 

### Logs
```
io.apicurio.registry.rest.client.exception.RestClientException: HTTP/1.1 header parser received no bytes
	at io.apicurio.registry.rest.client.impl.ErrorHandler.parseError(ErrorHandler.java:95)
	at io.apicurio.rest.client.JdkHttpClient.sendRequest(JdkHttpClient.java:207)
	at io.apicurio.registry.rest.client.impl.RegistryClientImpl.getContentByGlobalId(RegistryClientImpl.java:324)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:183)
	at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:142)
	at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:181)
	at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:141)
	at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:116)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:178)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:164)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:104)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:126)
	at io.apicurio.registry.utils.converter.SerdeBasedConverter.toConnectData(SerdeBasedConverter.java:139)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:516)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:516)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by EricWittmann** [comment]
Can you reproduce this error?  Any details on how often it happens?  Any specific steps to reproduce?

**Comment by Khan-Saad** [comment]
Hi, I'm encountering the exact same issue. Every ~30 mins to ~1 hour I receive this error, and it drops the request. I looked into the container logs to see if i can gain any insights but it doesn't log an error for this.

**Comment by nvlong198** [comment]
I got the same issue in the newest Registry Version: 2.4.2.final

**Comment by carlesarnal** [comment]
This is fixed on main with the use of the new client based on Kiota. We will provide instructions on how to migrate existing applications from one version to the other.
