### ISSUE TITLE
Apicurio Runtime issue - java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [Apicurio/apicurio-registry#3512]
**Problem Statement**

`apicurio-registry-utils-serde [1.3.2.Final]` seems to be having some internal dependency mismatch which leads to runtime issue when attempting to use `io.apicurio.registry.utils.serde.AvroKafkaSerializer` in value-deserializer. I did some digging and found that `io.apicurio:apicurio-registry-common:jar:1.3.2.Final` has a transitive dependency of `com.squareup.okhttp3:okhttp:jar:4.9.3` and `com.squareup.okio:okio:jar:2.8.0` which might be the root cause. The project is using Spring Boot + Kafka + Avro + Apicurio.

**Key Maven Dependencies**
```
<parent>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-parent</artifactId>
	<version>2.7.10</version
<parent>
<dependency>
	<groupId>org.springframework.kafka</groupId>
	<artifactId>spring-kafka</artifactId>
</dependency>
<dependency>
	<groupId>org.apache.avro</groupId>
	<artifactId>avro</artifactId>
	<version>1.11.1</version>
</dependency>
<dependency>
	<groupId>org.apache.avro</groupId>
	<artifactId>avro-tools</artifactId>
	<version>1.11.1</version>
</dependency>
<dependency>
	<groupId>io.apicurio</groupId>
	<artifactId>apicurio-registry-utils-serde</artifactId>
	<version>1.3.2.Final</version>
</dependency>
```

**Dependency Tree**
```
[INFO] +- io.apicurio:apicurio-registry-utils-serde:jar:1.3.2.Final:compile
[INFO] |  +- io.apicurio:apicurio-registry-rest-client:jar:1.3.2.Final:compile
[INFO] |  |  +- io.apicurio:apicurio-registry-common:jar:1.3.2.Final:compile
[INFO] |  |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO] |  |  |  \- com.squareup.okhttp3:okhttp:jar:4.9.3:compile
[INFO] |  |  |     \- com.squareup.okio:okio:jar:2.8.0:compile
[INFO] |  |  \- com.squareup.retrofit2:converter-jackson:jar:2.9.0:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.13.0:compile
[INFO] |  \- com.worldturner.medeia:medeia-validator-jackson:jar:1.1.1:compile
[INFO] |     +- com.worldturner.medeia:medeia-validator-core:jar:1.1.1:compile
[INFO] |     |  \- org.jetbrains.kotlin:kotlin-reflect:jar:1.6.21:compile
[INFO] |     \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.21:compile
[INFO] |        +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.21:compile
[INFO] |        \- org.jetbrains:annotations:jar:13.0:compile
[INFO] \- org.projectlombok:lombok:jar:1.18.26:compile
[INFO] -------------------------------------------------
```
**Error Stacktrace**
```
java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:71) ~[okhttp-4.9.3.jar:na]
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:309) ~[okhttp-4.9.3.jar:na]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41) ~[okhttp-4.9.3.jar:na]
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47) ~[okhttp-4.9.3.jar:na]
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:471) ~[okhttp-4.9.3.jar:na]
	at io.apicurio.registry.client.RegistryRestClientImpl.createHttpClientWithConfig(RegistryRestClientImpl.java:119) ~[apicurio-registry-rest-client-1.3.2.Final.jar:na]
	at io.apicurio.registry.client.RegistryRestClientImpl.<init>(RegistryRestClientImpl.java:97) ~[apicurio-registry-rest-client-1.3.2.Final.jar:na]
	at io.apicurio.registry.client.RegistryRestClientFactory.create(RegistryRestClientFactory.java:38) ~[apicurio-registry-rest-client-1.3.2.Final.jar:na]
	at io.apicurio.registry.client.CompatibleClient.<init>(CompatibleClient.java:61) ~[apicurio-registry-rest-client-1.3.2.Final.jar:na]
	at io.apicurio.registry.client.CompatibleClient.createCompatible(CompatibleClient.java:69) ~[apicurio-registry-rest-client-1.3.2.Final.jar:na]
	at io.apicurio.registry.utils.serde.AbstractKafkaSerDe.configure(AbstractKafkaSerDe.java:124) ~[apicurio-registry-utils-serde-1.3.2.Final.jar:na]
	at io.apicurio.registry.utils.serde.AbstractKafkaStrategyAwareSerDe.configure(AbstractKafkaStrategyAwareSerDe.java:75) ~[apicurio-registry-utils-serde-1.3.2.Final.jar:na]
	at io.apicurio.registry.utils.serde.AvroKafkaSerializer.configure(AvroKafkaSerializer.java:78) ~[apicurio-registry-utils-serde-1.3.2.Final.jar:na]
```

**Comment by carlesarnal** [comment]
I'm sorry but version 1.3.2.Final is no longer supported. I strongly suggest upgrading your version. Note that Apicurio Registry 2.0.0 was released more than two years ago.
