### ISSUE TITLE
Kafka Deserializer that can consume messages produced by e.g. ExtJsonConverter

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#4121]
### Feature or Problem Description
When using Debezium + Registry, the converter/connector produces messages on the Kafka topic in a specific format.  This format includes the schemaId and the payload, both wrapped in a JSON envelope.  We can consume that message in the context of the converter, but we don't have a standard Kafka deserializer that can do it.  Our current deserializers only handle formats produced by our serializers  (for obvious reasons).

### Proposed Solution
Create a new (or enhance an existing) deserializer that can consume a kafka message when formatted by our DBZ connector.

### Additional Context
Original issue reported in JIRA:  https://issues.redhat.com/browse/IPT-1044

### JIRA Description
Using `io.apicurio.registry.serde.jsonschema.JsonSchemaKafkaDeserializer` as deserializer, the sink application is not able to find the artifactId from the message and generate the following error:

```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:230)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:156)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:518)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:495)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:335)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:237)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:206)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:202)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:257)
    at org.apache.kafka.connect.runtime.isolation.Plugins.lambda$withClassLoader$1(Plugins.java:177)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: artifactId cannot be null
    at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByCoordinates(DefaultSchemaResolver.java:177)
    at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:172)
    at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
    at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:136)
    at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:131)
    at io.apicurio.registry.utils.converter.SerdeBasedConverter.toConnectData(SerdeBasedConverter.java:139)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$4(WorkerSinkTask.java:518)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:180)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:214)
    ... 14 more
```

The message consumed has the following structure:

```json
{
   "schemaId": 2,
   "payload": {
      "before": null,
      "after": {
         "id": 5,
         "first_name": "Test5",
         "last_name": "TEST5",
         "email": "test@test.com"
      },
      "source": {
         "version": "2.4.0.Final",
         "connector": "mysql",
         "name": "mysql",
         "ts_ms": 1701686545000,
         "snapshot": "false",
         "db": "inventory",
         "sequence": null,
         "table": "customers",
         "server_id": 1,
         "gtid": null,
         "file": "binlog.000002",
         "pos": 5063,
         "row": 0,
         "thread": 21,
         "query": null
      },
      "op": "c",
      "ts_ms": 1701686545582,
      "transaction": null
   }
}
```

Reproducer: https://github.com/aboucham/debezium/blob/main/examples/debezium-end2end.adoc#source-dbz--sink-kamelet---json-converter

**Comment by ranyhb** [comment]
Hi, i would like to know if anyone is working on this enhancement

**Comment by carlesarnal** [comment]
> Hi, i would like to know if anyone is working on this enhancement

Hello @ranyhb, 

Not for now, this has been included as a future feature for version 3 of the application. Are you interested in contributing?
