### ISSUE TITLE
Issue converting ArrayNode into JSONArray while validating schema

### ISSUE THREAD

**Issue by Gourav2912** [Apicurio/apicurio-registry#4125]
Hello Team,

Below line in code fail to convert ArrayNode into JSONArray while validating array schema
https://github.com/Apicurio/apicurio-registry/blob/fa0eb7d248abf128b2d71c5a0fcb223a8f6ef33b/serdes/jsonschema-serde/src/main/java/io/apicurio/registry/serde/jsonschema/JsonSchema.java#L206C19-L206C19
Error
Exception in thread "main" com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize value of type `org.json.JSONArray` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1746)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1520)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeFromArray(BeanDeserializer.java:648)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:211)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:187)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
	at com.fasterxml.jackson.databind.ObjectMapper.treeToValue(ObjectMapper.java:3343)

Schema Example 
{
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "type": "array",
  "items": {
    "type": "object",
    "additionalProperties": false,
    "required": [
      "abc",
      "xyz"
    ],
    "properties": {
      "abc": {
        "type": "string"
      },
      "xyz": {
        "type": "string"
      },
      "pqr": {
        "type": "string"
      }
    }
  }
}

Data
[
  {
  
  "abc":"1",
    "xyz":"xyz"
  
  }

]

**Comment by carlesarnal** [comment]
This has been fixed (we've replaced the library used in the serdes) in both main and in 2.5.11.Final.
