### ISSUE TITLE
Trying to run APICURI for SQL Image and facing below issues

### ISSUE THREAD

**Issue by heman00702** [Apicurio/apicurio-registry#4221]
```
I      at io.apicurio.registry.config.RegistryStorageConfigCache_ClientProxy.isAlive(Unknown Source)
        at io.apicurio.registry.storage.RegistryStorageProducer_ProducerMethod_realImpl_cf1c876861dd1c25dca504d30a12bfedeafd47bd_ClientProxy.isAlive(Unknown Source)
        at io.apicurio.registry.services.LogConfigurationService.checkLogLevel(LogConfigurationService.java:59)
        at io.apicurio.registry.services.LogConfigurationService_ClientProxy.checkLogLevel(Unknown Source)
        at io.apicurio.registry.services.LogConfigurationService_ScheduledInvoker_checkLogLevel_b78f9bb62877b2a9710d1be42f3febc6d0e16bd9.invokeBean(Unknown Source)
        at io.quarkus.scheduler.common.runtime.DefaultInvoker.invoke(DefaultInvoker.java:24)
        at io.quarkus.scheduler.common.runtime.StatusEmitterInvoker.invoke(StatusEmitterInvoker.java:35)
        at io.quarkus.scheduler.common.runtime.SkipConcurrentExecutionInvoker.invoke(SkipConcurrentExecutionInvoker.java:37)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask.doInvoke(SimpleScheduler.java:333)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:314)
        at io.quarkus.scheduler.runtime.SimpleScheduler$ScheduledTask$1.handle(SimpleScheduler.java:310)
        at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:581)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.postgresql.util.PSQLException: ERROR: column r.tenantid does not exist
  Position: 40
        at io.apicurio.registry.storage.impl.sql.jdb.QueryImpl.map(QueryImpl.java:65)
        at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.lambda$getGlobalRules$82(AbstractSqlRegistryStorage.java:2415)
        at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandle(HandleFactory.java:44)
        at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandleNoException(HandleFactory.java:52)
        ... 68 more
Caused by: org.postgresql.util.PSQLException: ERROR: column r.tenantid does not exist
  Position: 40
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
        at io.apicurio.registry.storage.impl.sql.jdb.MappedQueryImpl.<init>(MappedQueryImpl.java:50)
        at io.apicurio.registry.storage.impl.sql.jdb.QueryImpl.map(QueryImpl.java:63)
```

**Comment by heman00702** [comment]
... 61 more
Caused by: io.apicurio.registry.storage.impl.sql.jdb.RuntimeSqlException: org.postgresql.util.PSQLException: ERROR: relation "config" does not exist
  Position: 17
        at io.apicurio.registry.storage.impl.sql.jdb.QueryImpl.map(QueryImpl.java:65)
        at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.lambda$getRawConfigProperty$91(AbstractSqlRegistryStorage.java:2585)
        at io.apicurio.registry.storage.impl.sql.HandleFactory.withHandle(HandleFactory.java:44)
        at io.apicurio.registry.storage.impl.sql.HandleFactory_ClientProxy.withHandle(Unknown Source)
        at io.apicurio.registry.storage.impl.sql.AbstractSqlRegistryStorage.getRawConfigProperty(AbstractSqlRegistryStorage.java:2579)
        ... 145 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "config" does not exist
  Position: 17
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
        at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:134)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeQuery(PreparedStatementWrapper.java:78)
        at io.apicurio.registry.storage.impl.sql.jdb.MappedQueryImpl.<init>(MappedQueryImpl.java:50)
        at io.apicurio.registry.storage.impl.sql.jdb.QueryImpl.map(QueryImpl.java:63)

**Comment by heman00702** [comment]
the above two errors

**Comment by carlesarnal** [comment]
Hello,

We would need some more information to be able to help you, more specifically:

- How are you running the application?
- The version you're using.
- How are you configuring it?

That, along with a reproducer, would be very helpful. Otherwise is very hard for us to help you.

Thanks.

**Comment by heman00702** [comment]
Hi @carlesarnal  Sure, I am running this image  from an ec2 in aws and I have the connections open to interact with aurora postgresSql .. Here is my docker file config and I see all these tables are created on my postgres


version: '3.1'

services:
  postgres:
        image: postgres
        environment:
         POSTGRES_USER: ****
         POSTGRES_PASSWORD: ****
  app:
    image: apicurio/apicurio-registry:latest-snapshot
    ports:
      - 8080:8080
    environment:
      REGISTRY_STORAGE_KIND: 'sql'
      REGISTRY_STORAGE_DB_KIND: 'postgresql'
      REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://*****:5432/postgres'
      REGISTRY_DATASOURCE_USERNAME: ***
      REGISTRY_DATASOURCE_PASSWORD: ****
      
      
      
      
      Tables on postgres 
      
      
postgres=> \dt
             List of relations
 Schema |      Name      | Type  |  Owner
--------+----------------+-------+----------
 public | acls           | table | postgres
 public | apicurio       | table | postgres
 public | artifacts      | table | postgres
 public | comments       | table | postgres
 public | content        | table | postgres
 public | eventstreaming | table | postgres
 public | globalrules    | table | postgres
 public | groups         | table | postgres
 public | labels         | table | postgres
 public | properties     | table | postgres
 public | rules          | table | postgres
 public | versions       | table | postgres

**Comment by heman00702** [comment]
I tried this as well same result 

docker run -it -p 8080:8080 -e "REGISTRY_DATASOURCE_URL=jdbc:postgresql://*************:5432/postgres" -e "REGISTRY_DATASOURCE_USERNAME=******" -e "REGISTRY_DATASOURCE_PASSWORD=******" apicurio/apicurio-registry-sql:latest-release

**Comment by heman00702** [comment]
Could you please suggest any other way to install APICURIO and Storage as PostgresSql .. I want to do this all on AWS EC2

**Comment by heman00702** [comment]
@carlesarnal

**Comment by EricWittmann** [comment]
@heman00702 Could you post the full application logs?  It looks like the tables are all there.  I've never seen the specific error you're getting, but it seems you're missing the config table somehow.  The DDL it should be installing is here:

https://github.com/Apicurio/apicurio-registry/blob/main/app/src/main/resources/io/apicurio/registry/storage/impl/sql/postgresql.ddl

You could try dropping everything in the DB, enabling DEBUG logging, and then starting up again.  Then give us the full application logs, which will have a lot of information about what it's doing (e.g. installing the DDL).

You could **also** try installing the DDL yourself in a new DB instance and seeing what happens.  Perhaps the name of that table "config" is not allowed for whatever DB provider you're using?  That would surprise me because I would expect app startup to fail in the case.  And I'm assuming you're using an RDS instance for the DB.  We do that all the time without issue.

**Comment by carlesarnal** [comment]
So, I think know what the issue is here. You have created your application with an older version of the application, since looking a the first logs there is a log `column r.tenantid does not exist` which indicates that you're using an old version of the application. Now, looking at your docker-compose, you have upgraded the application image to the newest, snapshot one, and that would explain why you're missing a table in your database. I suggest dropping what you have in the database now and try starting the application again so it re-creates the database from scratch, that should solve your problem.

**Comment by heman00702** [comment]
cool .. yeah recreating everything fixed my issues.. thank you @EricWittmann  @carlesarnal  for your prompt responses
