### ISSUE TITLE
Can't redefine exception in the Client with AvroKafkaDeserializer

### ISSUE THREAD

**Issue by mrickly** [Apicurio/apicurio-registry#4463]
## Description

**Registry
Version**: 2.5.8.Final
**Persistence type**: "in-memory"

### Environment

Quarkus application in version 3.7.3 on my local machine. 
QuarkusTest using the KafkaCompanion and the Apicurio schema registry container.  

### Steps to Reproduce

Minimal Quarkus application with a QuarkusTest which uses the KafkaCompanion to write a message of the type defined by the avro schema below and deserializes it in an `@Incoming` method. 

```
{
  "type": "record",
  "name": "LeadFallErstellen",
  "namespace": "ch.mobi.lead.leadfall",
  "doc": "Schema for the fall erstellen topic",
  "fields": [
    {
      "name": "fall",
      "type": {
        "type": "record",
        "name": "Fall",
        "fields": [
          {
            "name": "verantwortlichkeitForFall",
            "type": [
              "null",
              {
                "type": "record",
                "name": "Verantwortlichkeit",
                "fields": [
                  {
                    "name": "benoetigteStellen",
                    "type": {
                      "type": "array",
                      "items": {
                        "type": "record",
                        "name": "FdtCodeArt",
                        "fields": [
                          {
                            "name": "art",
                            "type": "int"
                          },
                          {
                            "name": "code",
                            "type": "int"
                          }
                        ]
                      }
                    },
                    "default": []
                  }
                ]
              }
            ],
            "default": null
          }
        ]
      }
    },
    {
      "name": "aufgaben",
      "type": [
        "null",
        {
          "type": "array",
          "items": {
            "type": "record",
            "name": "Aufgabe",
            "fields": [
              {
                "name": "aufgabeTyp",
                "type": "FdtCodeArt"
              }
            ]
          }
        }
      ],
      "default": null
    }
  ]
}

```

### Expected vs Actual Behaviour

Expected: The message is deserialized without error (the Confluent Avro Deserializer works with this schema). 
Actual: SchemaParseException with "Can't redefine" (see stacktrace below).

### Logs

Caused by: org.apache.avro.SchemaParseException: Can't redefine: ch.mobi.lead.leadfall.FdtCodeArt
	at org.apache.avro.Schema$Names.put(Schema.java:1604)
	at org.apache.avro.Schema$Names.add(Schema.java:1598)
	at org.apache.avro.Schema.parse(Schema.java:1723)
	at org.apache.avro.Schema.parse(Schema.java:1736)
	at org.apache.avro.Schema.parse(Schema.java:1779)
	at org.apache.avro.Schema.parse(Schema.java:1823)
	at org.apache.avro.Schema.parse(Schema.java:1736)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1471)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1458)
	at io.apicurio.registry.serde.avro.AvroSchemaUtils.parse(AvroSchemaUtils.java:74)
	at io.apicurio.registry.serde.avro.AvroSchemaParser.parseSchema(AvroSchemaParser.java:58)
	at io.apicurio.registry.serde.avro.AvroSchemaParser.parseSchema(AvroSchemaParser.java:37)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:193)
	at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:201)
	at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:254)
	at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:200)
	at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:170)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:180)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:176)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:136)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:122)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.lambda$deserialize$1(DeserializerWrapper.java:77)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromItemSupplier.subscribe(UniCreateFromItemSupplier.java:28)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnFailureFlatMap.subscribe(UniOnFailureFlatMap.java:31)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:60)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at ch.mobi.gluon.messaging.kafka.internal.GluonDeserializationFailureHandler.decorateDeserialization(GluonDeserializationFailureHandler.java:33)
	at ch.mobi.gluon.messaging.kafka.internal.GluonDeserializationFailureHandler_ClientProxy.decorateDeserialization(Unknown Source)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.wrapDeserialize(DeserializerWrapper.java:97)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.deserialize(DeserializerWrapper.java:77)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:73)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:300)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:263)
	at org.apache.kafka.clients.consumer.internals.AbstractFetch.fetchRecords(AbstractFetch.java:340)
	at org.apache.kafka.clients.consumer.internals.AbstractFetch.collectFetch(AbstractFetch.java:306)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1262)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1186)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1159)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$poll$4(ReactiveKafkaConsumer.java:188)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.forwardTo(UniMemoizeOp.java:123)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:67)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more

**Comment by carlesarnal** [comment]
Hello,

Thanks for the report, this seems indeed like a bug. Let me try to reproduce it and I'll get back to you. If you have that code of the Quarkus application itself, that would be awesome.

**Comment by mrickly** [comment]
Hi @carlesarnal : Thank you for looking into this. I can supply a minimal Quarkus based reproducer.

**Comment by carlesarnal** [comment]
> Hi @carlesarnal : Thank you for looking into this. I can supply a minimal Quarkus based reproducer.

That would be awesome. Thanks!

**Comment by mrickly** [comment]
[apicurio-issue-4463.zip](https://github.com/Apicurio/apicurio-registry/files/14935549/apicurio-issue-4463.zip)
Here you are. If you do a clean install (or run the test after the classes have been generated by avro), you should see a stacktrace in the log similar to 
```
2024-04-10 19:23:13,284 WARN  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18228: A failure has been reported for Kafka topics '[fallerstellen]': org.apache.avro.SchemaParseException: Can't redefine: ch.mobi.lead.leadfall.FdtCodeArt
	at org.apache.avro.Schema$Names.put(Schema.java:1604)
	at org.apache.avro.Schema$Names.add(Schema.java:1598)
	at org.apache.avro.Schema.parse(Schema.java:1723)
	at org.apache.avro.Schema.parse(Schema.java:1736)
	at org.apache.avro.Schema.parse(Schema.java:1779)
	at org.apache.avro.Schema.parse(Schema.java:1823)
	at org.apache.avro.Schema.parse(Schema.java:1736)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1471)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1458)
	at io.apicurio.registry.serde.avro.AvroSchemaUtils.parse(AvroSchemaUtils.java:74)
	at io.apicurio.registry.serde.avro.AvroSchemaParser.parseSchema(AvroSchemaParser.java:58)
	at io.apicurio.registry.serde.avro.AvroSchemaParser.parseSchema(AvroSchemaParser.java:37)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaWithReferences(AbstractSchemaResolver.java:220)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.lambda$resolveSchemaByGlobalId$1(AbstractSchemaResolver.java:188)
	at io.apicurio.registry.resolver.ERCache.lambda$getValue$0(ERCache.java:201)
	at io.apicurio.registry.resolver.ERCache.retry(ERCache.java:254)
	at io.apicurio.registry.resolver.ERCache.getValue(ERCache.java:200)
	at io.apicurio.registry.resolver.ERCache.getByGlobalId(ERCache.java:170)
	at io.apicurio.registry.resolver.AbstractSchemaResolver.resolveSchemaByGlobalId(AbstractSchemaResolver.java:184)
	at io.apicurio.registry.resolver.DefaultSchemaResolver.resolveSchemaByArtifactReference(DefaultSchemaResolver.java:176)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.resolve(AbstractKafkaDeserializer.java:147)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.readData(AbstractKafkaDeserializer.java:136)
	at io.apicurio.registry.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:122)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.lambda$deserialize$1(DeserializerWrapper.java:77)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.wrapDeserialize(DeserializerWrapper.java:109)
	at io.smallrye.reactive.messaging.kafka.fault.DeserializerWrapper.deserialize(DeserializerWrapper.java:77)
	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:73)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.parseRecord(CompletedFetch.java:321)
	at org.apache.kafka.clients.consumer.internals.CompletedFetch.fetchRecords(CompletedFetch.java:283)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.fetchRecords(FetchCollector.java:168)
	at org.apache.kafka.clients.consumer.internals.FetchCollector.collectFetch(FetchCollector.java:134)
	at org.apache.kafka.clients.consumer.internals.Fetcher.collectFetch(Fetcher.java:145)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.pollForFetches(LegacyKafkaConsumer.java:693)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.poll(LegacyKafkaConsumer.java:617)
	at org.apache.kafka.clients.consumer.internals.LegacyKafkaConsumer.poll(LegacyKafkaConsumer.java:590)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at io.smallrye.reactive.messaging.kafka.impl.ReactiveKafkaConsumer.lambda$poll$4(ReactiveKafkaConsumer.java:188)
	at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransform$UniOnItemTransformProcessor.onItem(UniOnItemTransform.java:36)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onItem(UniOperatorProcessor.java:47)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.forwardTo(UniMemoizeOp.java:123)
	at io.smallrye.mutiny.operators.uni.UniMemoizeOp.subscribe(UniMemoizeOp.java:67)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```
