### ISSUE TITLE
Confluent compatibility api - create, delete and create schema with same name fails

### ISSUE THREAD

**Issue by famartinrh** [Apicurio/apicurio-registry#505]
Using confluent compatibility api, when a schema is created a validity rule is added to the created artifact, once the schema is deleted if you try to create a schema with the same name it will fail, in the registry logs this error can be found.
```
Caused by: io.apicurio.registry.storage.RuleAlreadyExistsException: A rule named 'VALIDITY' already exists.
	at io.apicurio.registry.storage.impl.AbstractMapRegistryStorage.createArtifactRule(AbstractMapRegistryStorage.java:450)
	at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_Subclass.createArtifactRule$$superaccessor109(InMemoryRegistryStorage_Subclass.zig:3338)
	at io.apicurio.registry.storage.impl.InMemoryRegistryStorage_Subclass$$function$$121.apply(InMemoryRegistryStorage_Subclass$$function$$121.zig:47)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.smallrye.metrics.interceptors.ConcurrentGaugeInterceptor.concurrentCallable(ConcurrentGaugeInterceptor.java:96)
	at io.smallrye.metrics.interceptors.ConcurrentGaugeInterceptor.countedMethod(ConcurrentGaugeInterceptor.java:69)
	at io.smallrye.metrics.interceptors.ConcurrentGaugeInterceptor_Bean.intercept(ConcurrentGaugeInterceptor_Bean.zig:215)
```
There is a test in PR #502 to reproduce the issue.

**Comment by EricWittmann** [comment]
This is because when creating an artifact with the ccompat API we auto-create the VALIDITY rule **and** we fail to delete all artifact rules when an artifact is deleted.  The second part of that is the bug.
