### ISSUE TITLE
Extra "schemaType" field (ccompat)

### ISSUE THREAD

**Issue by ahamidi** [Apicurio/apicurio-registry#552]
While trying to setup the registry for use with Kafka Connect I encountered the following exception:

```
org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic pg-cdc-avro.public.spree_orders to Avro: 
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:110)
	at org.apache.kafka.connect.storage.Converter.toConnectData(Converter.java:87)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$2(WorkerSinkTask.java:492)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
	at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:492)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:469)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:325)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:228)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:196)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 106
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "schemaType" (class io.confluent.kafka.schemaregistry.client.rest.entities.SchemaString), not marked as ignorable (one known property: "schema"])
```
I can see the field `schemaType` in the response (with the value `AVRO`).

Looking at the [Confluent docs](https://docs.confluent.io/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id) it looks like the response should only include the field `schema`:
```
HTTP/1.1 200 OK
Content-Type: application/vnd.schemaregistry.v1+json

{
  "schema": "{\"type\": \"string\"}"
}
```

Looking at the code I can see that there's an explicit `KConnect` schema type supported but the schema is being automatically registered by Kafka Connect as `Avro`. Out of curiousity I tried to manually upload a schema and set it to `KConnect` but it still responds with the `schemaType` field anyway.

Is there something that I should be doing differently to prevent that field from being included or is this a case of incompatibility with the Confluent Schema Registry?

**Comment by EricWittmann** [comment]
Without looking deeper into the problem I'm going to say it's likely a bug in our implementation.  We recently upgraded our compatibility API to the latest functionality in the Confluent registry, but it's possible we introduced a bug.  The concept of Schema Type was only just introduced.

@carlesarnal I think `SchemasResource::getSchema()` needs to return a `SchemaContent` variant without the `schemaType` property.

@ahamidi please note that KConnect is a type that is supported by the Apicurio Registry but not the Confluent Registry - it refers to the Avro-like (but non-Avro as I understand it) schema format often used in Kafka Connect.  The only way to use that format is by switching to Apicurio Registry's API and SerDes/Connectors.  It seems like that's not needed for your use-case, I just wanted to clarify.
