### ISSUE TITLE
tests - unstable KafkaConnectConverterIT

### ISSUE THREAD

**Issue by famarting** [Apicurio/apicurio-registry#568]
Recently new test has been added to test apicurio's kafka connect converters + debeizum from the suggestion in issue #500

Test is flaky and sometimes pass and sometimes don't. Trying to fix that I increased several timeous, included the timeout for the container to start. But looks like test keeps failing anyway.

The error I've seen the most is about timing out to start the debezium container
```
2020-05-29T13:29:42.8783499Z org.testcontainers.containers.ContainerLaunchException: Timed out waiting for URL to be accessible (http://localhost:32776/connectors should return HTTP [200])
2020-05-29T13:29:42.8804044Z 	at org.testcontainers.containers.wait.strategy.HttpWaitStrategy.waitUntilReady(HttpWaitStrategy.java:214) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8804924Z 	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8805496Z 	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:876) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8806032Z 	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:428) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8806554Z 	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:317) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8807063Z 	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81) ~[duct-tape-1.0.8.jar:?]
2020-05-29T13:29:42.8807578Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:315) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8808080Z 	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:302) ~[testcontainers-1.12.4.jar:?]
2020-05-29T13:29:42.8808592Z 	at io.apicurio.tests.converters.KafkaConnectConverterIT.startContainers(KafkaConnectConverterIT.java:219) ~[test-classes/:?]
```

I've copied the complete test run logs from GH actions into this gist, If you look for KafkaConnectConverterIT you'll find the log I'm referring to
https://gist.githubusercontent.com/famartinrh/9ef49cf8628bf18db2529705ef01bed9/raw/dcf95c1623967a603034b565bc0a3b7d80e858d7/kafka%2520connect%2520converter%2520it%2520fails

maybe @jpechane could help us here identifiying in the logs what could be the reason that makes debezium container to fail to start up.

**Comment by EricWittmann** [comment]
Thanks @famartinrh - this is a very useful test but yes, it's too flaky.  We might need to turn it off temporarily until we can improve it.

**Comment by jpechane** [comment]
I'd recommend to increase the timeout. From the log I can say that the Kafka Connect initialization was still in progress when the wait for url timeouted.

**Comment by carlesarnal** [comment]
Closing as this test no longer exists.
