### ISSUE TITLE
Maven Plugin : Vert.x not shut down cleanly

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#5683]
Not sure if this is caused by the preceding upload errors, but the Maven build always ends with an exception that is https://github.com/vert-x3/issues/issues/288 by Vert.x still running in the background while the plugin's class realm is torn down:

```
Exception in thread "Thread-4" java.lang.NoClassDefFoundError: io/vertx/core/file/impl/FileSystemImpl$11
        at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:898)
        at io.vertx.core.file.impl.FileCache.deleteCacheDir(FileCache.java:140)
        at io.vertx.core.file.impl.FileCache.lambda$runHook$0(FileCache.java:92)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.impl.FileSystemImpl$11
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)
        ... 4 more
```

**Comment by EricWittmann** [comment]
Reproducer:

[issue5683-reproducer.zip](https://github.com/user-attachments/files/18041898/issue5683-reproducer.zip)

Just start up a Registry server and then run:

```
mvn test
```

Output:

```
~/issue5683-reproducer$ mvn test
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------< io.apicurio.issues:issue-5683-reproducer >--------------
[INFO] Building issue-5683-reproducer 1
[INFO]   from pom.xml
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- apicurio-registry:3.0.6-SNAPSHOT:register (register-artifact) @ issue-5683-reproducer ---
[INFO] Successfully registered artifact [default] / [SearchRequest].  GlobalId is [2]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.067 s
[INFO] Finished at: 2024-12-06T12:52:41-05:00
[INFO] ------------------------------------------------------------------------
Exception in thread "Thread-3" java.lang.NoClassDefFoundError: io/vertx/core/file/impl/FileSystemImpl$11
	at io.vertx.core.file.impl.FileSystemImpl.delete(FileSystemImpl.java:898)
	at io.vertx.core.file.impl.FileCache.deleteCacheDir(FileCache.java:140)
	at io.vertx.core.file.impl.FileCache.lambda$runHook$0(FileCache.java:92)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: io.vertx.core.file.impl.FileSystemImpl$11
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:225)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:210)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:205)
	... 4 more
```
