### ISSUE TITLE
NPE searching for artifacts via Streams storage variant with multiple pods

### ISSUE THREAD

**Issue by EricWittmann** [Apicurio/apicurio-registry#661]
We're getting the following NPE:

```
Caused by: java.lang.NullPointerException
	at io.apicurio.registry.streams.distore.proto.FilterReq$Builder.setFilter(FilterReq.java:590)
	at io.apicurio.registry.streams.distore.ReadOnlyKeyValueStoreGrpcClient.filter(ReadOnlyKeyValueStoreGrpcClient.java:57)
	at io.apicurio.registry.streams.distore.DistributedReadOnlyKeyValueStore.lambda$filter$0(DistributedReadOnlyKeyValueStore.java:86)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2191)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2157)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
```

The issue is that `null` is a valid value for the "search" criteria at the jax-rs layer, but not at the protobuf layer within the Streams storage impl.  So we need to convert `null` into empty string.

**Comment by EricWittmann** [comment]
Fixed by https://github.com/EricWittmann/apicurio-registry/commit/8cfff39affd13b870b68f8e7c4af69e0b3839dc3
