### ISSUE TITLE
Apicurio registry client does not work with jersey http client

### ISSUE THREAD

**Issue by praburajan** [Apicurio/apicurio-registry#711]
We are switching to apicurio schema registry from confluent schema registry. We are hitting an issue with the apicurio registry client relying on jboss resteasy http client. The issue is that, when both jersey and resteasy jaxrs providers are in the classpath, resteasy takes precedence and it breaks our other functionality that uses Http client relying on jersey client's support for application/octet-stream transport, which resteasy does not seem to support.

```
Caused by:
        javax.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
            at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:286)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:488)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:65)
            at org.jboss.resteasy.client.jaxrs.internal.ClientInvocationBuilder.put(ClientInvocationBuilder.java:208)
            at com.oracle.bmc.http.internal.ForwardingInvocationBuilder.put(ForwardingInvocationBuilder.java:142)
            at com.oracle.bmc.http.internal.RestClient.lambda$put$9(RestClient.java:448)
            at com.oracle.bmc.http.internal.RestClient.put(RestClient.java:448)
            ... 12 more
            Caused by:
            javax.ws.rs.ProcessingException: RESTEASY003215: could not find writer for content-type application/octet-stream type: com.oracle.bmc.io.internal.KeepOpenInputStream
                at org.jboss.resteasy.core.interception.jaxrs.ClientWriterInterceptorContext.throwWriterNotFoundException(ClientWriterInterceptorContext.java:50)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getWriter(AbstractWriterInterceptorContext.java:302)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:240)
                at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.proceed(AbstractWriterInterceptorContext.java:224)
                at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.writeRequestBody(ClientInvocation.java:440)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.writeRequestBodyToOutputStream(ManualClosingApacheHttpClient43Engine.java:584)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.buildEntity(ManualClosingApacheHttpClient43Engine.java:547)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.loadHttpMethod(ManualClosingApacheHttpClient43Engine.java:454)
                at org.jboss.resteasy.client.jaxrs.engines.ManualClosingApacheHttpClient43Engine.invoke(ManualClosingApacheHttpClient43Engine.java:264)
                ... 18 more
```

**Comment by EricWittmann** [comment]
Can you exclude RESTEasy from the classpath?  Our client **should** work with Jersey if that's what is on the classpath.

**Comment by EricWittmann** [comment]
Also we are working on replacing our current client with a new version that does not require RESTEasy or Jersey.  It should be available in the next release.

**Comment by EricWittmann** [comment]
Update: the next release of Apicurio Registry will use the new client.  That work has been completed and is checked into the `master` branch.  Have a look now or wait for the 1.3.0.Final release we should be doing this week.

**Comment by tomasAlabes** [comment]
@EricWittmann I'm facing what seems to be an incompatibility too but with jersey (using 1.3.0.Final)

```
Caused by: java.lang.IllegalStateException: Method not supported on an outbound message.
        at org.glassfish.jersey.message.internal.OutboundJaxrsResponse.readEntity(OutboundJaxrsResponse.java:137)
        at io.apicurio.registry.utils.serde.AvroKafkaDeserializer.toSchema(AvroKafkaDeserializer.java:75)
        at io.apicurio.registry.utils.serde.AvroKafkaDeserializer.toSchema(AvroKafkaDeserializer.java:39)
        at io.apicurio.registry.utils.serde.AbstractKafkaDeserializer$1.toSchema(AbstractKafkaDeserializer.java:44)
        at io.apicurio.registry.utils.serde.SchemaCache.lambda$getSchema$0(SchemaCache.java:52)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.apicurio.registry.utils.serde.SchemaCache.getSchema(SchemaCache.java:40)
        at io.apicurio.registry.utils.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:74)
        at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
        at org.springframework.kafka.support.serializer.ErrorHandlingDeserializer.deserialize(ErrorHandlingDeserializer.java:187)
        ... 15 common frames omitted
```

**Comment by EricWittmann** [comment]
Update: as of release 1.3.0.Final we no longer rely on either RESTEasy or Jersey for our client.  The client is now much simpler and built using Retrofit.  So the underlying http client is now the `OkHttpClient`.  Hopefully this resolves the problem.

**Comment by EricWittmann** [comment]
@praburajan If you have some time to give 1.3.0.Final a try that would be super helpful. :)

**Comment by tomasAlabes** [comment]
Hi @EricWittmann, I tried but had to file #808. A lot of exclude's and extra dependencies were able to get removed though.

**Comment by EricWittmann** [comment]
Thank you!

**Comment by EricWittmann** [comment]
The client in `1.3.1.Final` should be even better!  We've removed a lot of the jax-rs classes we were leaning on.  Version `1.3.1.Final` should be out in the next few days.  If you could give that a try when the time comes, I would appreciate it.

**Comment by carlesarnal** [comment]
I guess we can close this.
