### ISSUE TITLE
Client not compatible with Jersey

### ISSUE THREAD

**Issue by tomasAlabes** [Apicurio/apicurio-registry#808]
Using 1.3.0.Final, I'm facing what seems to be an incompatibility with jersey:

```
Caused by: java.lang.IllegalStateException: Method not supported on an outbound message.
        at org.glassfish.jersey.message.internal.OutboundJaxrsResponse.readEntity(OutboundJaxrsResponse.java:137)
        at io.apicurio.registry.utils.serde.AvroKafkaDeserializer.toSchema(AvroKafkaDeserializer.java:75)
        at io.apicurio.registry.utils.serde.AvroKafkaDeserializer.toSchema(AvroKafkaDeserializer.java:39)
        at io.apicurio.registry.utils.serde.AbstractKafkaDeserializer$1.toSchema(AbstractKafkaDeserializer.java:44)
        at io.apicurio.registry.utils.serde.SchemaCache.lambda$getSchema$0(SchemaCache.java:52)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.apicurio.registry.utils.serde.SchemaCache.getSchema(SchemaCache.java:40)
        at io.apicurio.registry.utils.serde.AbstractKafkaDeserializer.deserialize(AbstractKafkaDeserializer.java:74)
        at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:60)
        at org.springframework.kafka.support.serializer.ErrorHandlingDeserializer.deserialize(ErrorHandlingDeserializer.java:187)
        ... 15 common frames omitted
```

This is because the function `parseResponseBody` of `apicurio-registry-client-1.3.0.Final.jar`'s class `RegistryRestClientImpl` creates an outbound request that later cannot be read. Because jersey's `readEntity` method is disabled on server side outbound responses.

I'm using `jersey 2.30.1`.

**Comment by alesj** [comment]
What does one use then to read REST content in Jersey?

**Comment by tomasAlabes** [comment]
They way I temporarily hacked it is like this:

```kotlin
override fun toSchema(response: Response): Schema {
    return AvroSchemaUtils.parse(String((response.entity as InputStream).readAllBytes()))
}
```

But, I guess something smarter can be done with the `response.getEntity()` (the entity of the `OutboundJaxrsResponse` can't be read, but it can be get).

Or you could avoid using `Response` directly from the `RegistryRestClientImpl` and pass something different up the chain. Like the `ResponseBody` itself, something custom, the bytestream, etc.

Just ideas, hope they help.

**Comment by EricWittmann** [comment]
Yeah I mentioned to @carlesarnal that we may want to not use JAX-RS classes in the new client if we can avoid it.  Otherwise I think we're going to continue having Jersey vs. RESTEasy problems.

**Comment by EricWittmann** [comment]
For a workaround, see this:  https://github.com/Apicurio/apicurio-registry/issues/702#issuecomment-688248363

**Comment by rjcruz** [comment]
Thanks for the quick fix! Are there any plans for a minor release soon to include this?

**Comment by EricWittmann** [comment]
There should be a minor release relatively soon (within the next week or two), yes.  Be aware that the fix to the new client interface does not fix the problem when using our serdes classes.  For now, the serdes classes still use some JAX-RS code because they are still using the old client interface.  We can't change this until a major release, since it would represent a breaking change.
