### ISSUE TITLE
Failed to get offsets by times - Registry with Kafka 

### ISSUE THREAD

**Issue by weimeilin79** [Apicurio/apicurio-registry#969]
I follow the documentation to start the registry kafka instance, but was not able to get it working.

I kept getting this error.

```
2020-10-30 14:04:32,322 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka commitId: 66563e712b0b9f84
2020-10-30 14:04:32,323 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka startTimeMs: 1604066672310
2020-10-30 14:04:32,326 INFO  [io.api.reg.uti.kaf.ConsumerContainer] (kafka-consumer-container-1) Consumer is not subscribed to any topics or assigned any partitions - will wait
2020-10-30 14:04:32,327 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (main) [Consumer clientId=consumer-2, groupId=null] Subscribed to partition(s): snapshot-topic-0
2020-10-30 14:05:02,347 ERROR [io.qua.application] (main) Failed to start application (with profile prod): org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times in 30000ms

```

Is there a way to turn on the debug mode, so I get to see more info on what's going on?

**Comment by EricWittmann** [comment]
You can set the env var `LOG_LEVEL` to `DEBUG` and see what you get.

@alesj any idea what the error means?

**Comment by weimeilin79** [comment]
Maybe it's because I was using Mac? First I used the setting and set the _bootstrap_server_ to *host.docker.internal:9092* and it would not take it, so I manually resolve the ip to `192.168.65.2`, so it was able to locate it, but after I set it to `192.168.65.2` 

```
docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=192.168.65.2:9092" -e "LOG_LEVEL=DEBUG" apicurio/apicurio-registry-kafka:latest
```


I don't know why, it still connects to *localhost/127.0.0.1* ?? 


```
ss localhost/127.0.0.1
2020-11-01 21:07:03,308 DEBUG [org.apa.kaf.com.net.Selector] (main) [Consumer clientId=consumer-2, groupId=null] Connection with localhost/127.0.0.1 disconnected: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:220)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:530)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:549)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:224)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:161)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchOffsetsByTimes(Fetcher.java:552)
	at org.apache.kafka.clients.consumer.internals.Fetcher.beginningOrEndOffset(Fetcher.java:576)
	at org.apache.kafka.clients.consumer.internals.Fetcher.endOffsets(Fetcher.java:564)
	at org.apache.kafka.clients.consumer.KafkaConsumer.endOffsets(KafkaConsumer.java:2232)
	at org.apache.kafka.clients.consumer.KafkaConsumer.endOffsets(KafkaConsumer.java:2204)
	at io.apicurio.registry.kafka.RegistryConsumerContainer.loadSnapshot(RegistryConsumerContainer.java:107)
	at io.apicurio.registry.kafka.RegistryConsumerContainer.start(RegistryConsumerContainer.java:72)
	at io.apicurio.registry.kafka.KafkaRegistryConfiguration_ProducerMethod_registryContainer_b3c72d7e63c419748d3607daeb498040c290b283_ClientProxy.start(KafkaRegistryConfiguration_ProducerMethod_registryContainer_b3c72d7e63c419748d3607daeb498040c290b283_ClientProxy.zig:228)
	at io.apicurio.registry.kafka.KafkaRegistryConfiguration.init(KafkaRegistryConfiguration.java:133)
	at io.apicurio.registry.kafka.KafkaRegistryConfiguration_Observer_init_e83f9501608aa67d99389d54160a9495549f5bbe.notify(KafkaRegistryConfiguration_Observer_init_e83f9501608aa67d99389d54160a9495549f5bbe.zig:179)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:113)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:598)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)

```

**Comment by alesj** [comment]
@weimeilin79 is there a particular reason why you're testing Kafka storage instead of (supported) Streams storage?
apicurio/apicurio-registry-kafka:latest --> apicurio/apicurio-registry-streams:latest

**Comment by weimeilin79** [comment]
You might want to remove the document if the version is not working (I just pick whatever first came in the doc, I thought streams and Kafka should  works the same... )
https://www.apicur.io/registry/docs/apicurio-registry/1.3.1.Final/getting-started/assembly-installing-the-registry-docker.html#installing-registry-kafka-storage

`docker run -it -p 8080:8080 -e "KAFKA_BOOTSTRAP_SERVERS=192.168.65.2:9092" apicurio/apicurio-registry-streams:latest` 

and after switching to streams, I got this error, looks like it's not using the 9092 port? Is this doc up to date?
https://www.apicur.io/registry/docs/apicurio-registry/1.3.1.Final/getting-started/assembly-installing-the-registry-docker.html#installing-registry-kafka-streams-storage

```
2020-11-02 13:41:31,618 DEBUG [org.apa.kaf.com.net.Selector] (my-kafka-streams-app-22940aa5-cbd5-4c7c-bd90-6c97a83a4878-StreamThread-1) [Consumer clientId=my-kafka-streams-app-22940aa5-cbd5-4c7c-bd90-6c97a83a4878-StreamThread-1-consumer, groupId=my-kafka-streams-app] Connection with /192.168.65.2 disconnected: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.apache.kafka.common.network.PlaintextTransportLayer.finishConnect(PlaintextTransportLayer.java:50)
	at org.apache.kafka.common.network.KafkaChannel.finishConnect(KafkaChannel.java:220)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:530)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:549)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:262)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:233)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollForFetches(KafkaConsumer.java:1308)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1248)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1216)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:853)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:753)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:697)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:670)
```

**Comment by alesj** [comment]
> You might want to remove the document if the version is not working 

It should work, it's just not priority / supported.

The doc looks fine, it's how you run and expose Kafka broker to Registry running in Docker.
I know this was always an issue on OSX -- not just for Kafka ...

Check this demo if it helps you:
* https://github.com/Apicurio/apicurio-registry-demo

**Comment by weimeilin79** [comment]
Yes, running it without the container worked! Must be network issue in MacOS, Thanks!! @alesj

**Comment by EricWittmann** [comment]
Also note: the kafka impl has been deprecated for awhile.  I just removed it from `master` to avoid this confusion going forward. :)
