### ISSUE TITLE
Upload of bad schema shows cryptic message

### ISSUE THREAD

**Issue by pilhuhn** [Apicurio/apicurio-registry#997]
I tried to upload a (bad) schema (see attachment) via the UI and got the following reply:

```
io.apicurio.registry.storage.InvalidArtifactTypeException: Failed to discover artifact type from content.
	at io.apicurio.registry.util.ArtifactTypeUtil.discoverType(ArtifactTypeUtil.java:133)
	at io.apicurio.registry.rest.ArtifactsResourceImpl.determineArtifactType(ArtifactsResourceImpl.java:150)
	at io.apicurio.registry.rest.ArtifactsResourceImpl.createArtifact(ArtifactsResourceImpl.java:325)
	at io.apicurio.registry.rest.ArtifactsResourceImpl_Subclass.createArtifact$$superaccessor19(ArtifactsResourceImpl_Subclass.zig:3849)
	at io.apicurio.registry.rest.ArtifactsResourceImpl_Subclass$$function$$19.apply(ArtifactsResourceImpl_Subclass$$function$$19.zig:53)

```

While it is correct, it does not help the user. The registry should show the parser error

E.g. with `avro_validator` the following is printed:

```
$ avro_validator test1.avsc test1.avsc
Error parsing the schema. Problem found:
 Expecting ',' delimiter: line 21 column 1 (char 330)
```

[test1.avsc.txt](https://github.com/Apicurio/apicurio-registry/files/5516384/test1.avsc.txt)

**Comment by EricWittmann** [comment]
What do you get if you tell us what the artifact type is?  I'm assuming you didn't specify a type in the UI when uploading the bad schema?  If that is the case, the server is going to attempt to figure out what the type is... but if the content can't be parsed by any of the supported parsers (avro, protobuf, json schema, openapi, etc) then we can't figure out what it is ... and thus we can't tell you what the parser error is.  We could pick one of the parsers at random and give you the output of that, but the odds are we'd be wrong.

**Comment by pilhuhn** [comment]
Good point, thank for the hint. Would it make sense in the case that the type can not be determined to show a message to the user that the type could not be determined and that the user needs to select one instead of showing a stack trace?

With setting the type to Avro and the default (global) settings out of the box, the bad schema is just accepted. Only when I first go to preferences and enable validation, it is flagged as bad. Unfortunately in another cryptic way:

![Bildschirmfoto 2020-11-10 um 14 34 18](https://user-images.githubusercontent.com/208246/98680544-d65ab200-2361-11eb-9054-3b20aaf5365f.png)

Only after I scroll down I get the real reason and a hint about what is wrong (below). I think it would be good to only show the inner exception (and only once). Also perhaps try to validate for valid json if the upload is a json-based type and reject it no matter what the validation settings are, because here the result in the registry is nothing anyone can work with (IMO).

```
Caused by: org.apache.avro.SchemaParseException: com.fasterxml.jackson.core.JsonParseException: Unexpected close marker '}': expected ']' (for Array starting at [Source: (String)"{
  "namespace": "de.pilhuhn.kafka.play",
  "type": "record",
  "name": "test1",
  "fields": [
     {
        "name": "name",
        "type": "string"
     },
     {
        "name": "number",
        "type": "integer"
     },
     {
        "name": "checkbox",
        "type": [
           true,
           false
        ]
     }
}


"; line: 5, column: 13])
 at [Source: (String)"{
  "namespace": "de.pilhuhn.kafka.play",
  "type": "record",
  "name": "test1",
  "fields": [
     {
        "name": "name",
        "type": "string"
     },
     {
        "name": "number",
        "type": "integer"
     },
     {
        "name": "checkbox",
        "type": [
           true,
           false
        ]
     }
}


"; line: 21, column: 2]
	at org.apache.avro.Schema$Parser.parse(Schema.java:1427)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1413)
	at io.apicurio.registry.rules.validity.AvroContentValidator.validate(AvroContentValidator.java:45)
	... 117 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected close marker '}': expected ']' (for Array starting at [Source: (String)"{
  "namespace": "de.pilhuhn.kafka.play",
  "type": "record",
  "name": "test1",
  "fields": [
     {
        "name": "name",
        "type": "string"
     },
     {
        "name": "number",
        "type": "integer"
     },
     {
        "name": "checkbox",
        "type": [
           true,
           false
        ]
     }
}


"; line: 5, column: 13])
 at [Source: (String)"{
  "namespace": "de.pilhuhn.kafka.play",
  "type": "record",
  "name": "test1",
  "fields": [
     {
        "name": "name",
        "type": "string"
     },
     {
        "name": "number",
        "type": "integer"
     },
     {
        "name": "checkbox",
        "type": [
           true,
           false
        ]
     }
}


"; line: 21, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1851)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:707)
	at com.fasterxml.jackson.core.base.ParserBase._reportMismatchedEndMarker(ParserBase.java:1016)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._closeScope(ReaderBasedJsonParser.java:2919)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:684)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:434)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:261)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4497)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2840)
	at org.apache.avro.Schema$Parser.parse(Schema.java:1425)
	... 119 more

```

**Comment by EricWittmann** [comment]
Yes I agree with your suggestions for improving the UX.  We've done some work in that area for the next major version, but not these specific issues I don't think.
